### ISSUE TITLE
Keep development out of master

### ISSUE THREAD

**Issue by danielchatfield** [mitsuhiko/flask#1127]
Convention is (and rightly so) that the master branch is stable. There have been several issues lately that are related to the accidental use of the development version.

Also the docs [here](http://flask.readthedocs.org/) track the development version so you can hardly blame someone for getting stuck trying to follow them when they have loads of stuff that doesn't apply to the current stable version.

Can we make an effort to sort this out?

**Comment by davidism** [comment]
Closing this since the docs have a dev and 0.10 version now, and the branching strategy seems to be working for the team.
