### ISSUE TITLE
consider adding CC-BY license for documentation only

### ISSUE THREAD

**Issue by eshellman** [mitsuhiko/flask#1154]
Many channels for distribution of documentation (Internet Archive, most libraries) find it easier to distribute the documentation if it is Creative Commons (CC) licensed -  they aren't able to spend the time to read a custom license, even if it's just a modified Apache License. But for documentation only, there's really no difference between the Flask license and CC-BY http://creativecommons.org/licenses/by/4.0/

**Comment by untitaker** [comment]
That would complicate things in the sense that Flask (the distribution as a whole) now has two licenses.

Afaik you're the first one to request this... therefore I'll close this issue for now.
