### ISSUE TITLE
Confusing line in Uploading Files pattern documentation

### ISSUE THREAD

**Issue by jhorneman** [mitsuhiko/flask#1256]
flask/blob/master/docs/patterns/fileuploads.rst, after the first bit of sample code, says:

"Then we add a URL rule by hand to the application."

But I see no place in that code where a URL rule is added.

Expected: Either a URL rule is added in that piece of code, or the text doesn't state that that happens.

**Comment by sourya** [comment]
The rule is specified before the ```uploaded_file()``` function:
```@app.route(’/uploads/<filename>’)```

**Comment by untitaker** [comment]
Patches welcome. :-)

**Comment by sourya** [comment]
I've created a pull request fixing this issue.

**Comment by keyanp** [comment]
@untitaker I think this can be closed.

**Comment by untitaker** [comment]
Yup, thanks again @sourya!

**Comment by sourya** [comment]
:)
