### ISSUE TITLE
Python 3.4 and PyCharm breakpoints when use_reloader=True

### ISSUE THREAD

**Issue by msurdi** [mitsuhiko/flask#1261]
Running a flask application with debug=True (and thus, use_reloader=True) in Pycharm, breakpoints inside view functions don't work. Setting use_reloader=False works, but I miss the reloader. This works as expected when running on Python 2.7. I'm not sure if this is an issue on Flask, Werkzeug or Pycharm. Is there somebody with better insights on Werkzeug internals and  how the Pycharm debugger works that could help me with this?.

**Comment by mozey** [comment]
I have the same problem with python 3.3.5 and pycharm 3.4.1

**Comment by untitaker** [comment]
There are no behavioral differences by Flask between Py2 and Py3.

I suppose that PyCharm doesn't correctly track the PID of the new process, but I'm not entirely sure. I don't think this is an issue Flask/Werkzeug should solve, but I'll leave this issue open anyway. Please refrain from adding :+1: though.

**Comment by mozey** [comment]
Just one more please :) Link to issue on pycharm tracker here:
https://youtrack.jetbrains.com/issue/PY-14864

**Comment by untitaker** [comment]
Thanks for the link.

**Comment by RonnyPfannschmidt** [comment]
tbh i think pycharm should ship a own wsgi server with total controll over breakpoints and restarting
if thats not part of their flask/django/wsgianything integration anyway they are slacking

**Comment by untitaker** [comment]
That'd be the most powerful solution, yes.

**Comment by davidism** [comment]
Seems to be fixed.  I can set a breakpoint in the view in the following example and the debugger activates correctly.

~~~python
from flask import Flask

app = Flask(__name__)

@app.route('/')
def index():
    return 'Hello, World!'

app.run(debug=True)
~~~
