### ISSUE TITLE
`itsdangerous` dependency not marked

### ISSUE THREAD

**Issue by larkost** [mitsuhiko/flask#1284]
It appears (at least in version 10.1) that there is a dependency on the `its dangerous` module. This is not in the standard library (at least on MacOS), so at least should be added to the dependencies listed in the first paragraph of http://flask.pocoo.org/docs/0.10/installation/

**Comment by sfermigier** [comment]
The doc now says "Flask depends on **some** external libraries, like `Werkzeug
<http://werkzeug.pocoo.org/>`_ and `Jinja2 <http://jinja.pocoo.org/>`_."  (I'm the one highlighting "some").

Can we close this issue ?

**Comment by untitaker** [comment]
Huh, this seems to be fixed in master before this issue has been opened.
