### ISSUE TITLE
Links to PDF and HTML Zipped Docs return 404 error

### ISSUE THREAD

**Issue by texpilot** [mitsuhiko/flask#1300]
Trying to download the PDF version of the flask docs from URL http://flask.pocoo.org returns error code 404. Same thing with the HTML Zipped link.

Looking forward to getting into Flask!

**Comment by aliasm2k** [comment]
Documentation on flask is available from http://flask.readthedocs.org/ 

Dive into flask. Don't wait. Regarding the PDF or HTML Zipped link, didn't find it there (http://flask.pocoo.org) anywhere.

**Comment by aliasm2k** [comment]
This issue has already been reported https://github.com/mitsuhiko/flask/issues/1251

**Comment by texpilot** [comment]
Thanks Karthik.

The "PDF" and “zipped HTML” links are right on the home page (http://flask.pocoo.org <http://flask.pocoo.org/>), under the “Interested?” section:

Interested?
Download latest release <http://pypi.python.org/packages/source/F/Flask/Flask-0.10.1.tar.gz> (0.10.1)
Read the documentation <http://flask.pocoo.org/docs/> or download as PDF <http://flask.pocoo.org/docs/flask-docs.pdf> and zipped HTML <http://flask.pocoo.org/docs/flask-docs.zip>
<…>

FYI, the “as PDF”, “as ePub”, “as .mobi”, “as zipped HTML” links at http://flask.readthedocs.org/en/latest/ also all return 404 Not Found as well.

**Comment by aliasm2k** [comment]
It seems like the people at pocoo are working on this documentation issue. Issue https://github.com/pocoo/metaflask/issues/7
