### ISSUE TITLE
request.form issue

### ISSUE THREAD

**Issue by aliasm2k** [mitsuhiko/flask#1305]
Just encountered this issue. Don't know if it had already been reported.
Using `request.form['field']` to access checkbox doesnot work; whereas `request.form.get('field')` works. It is possible to use both `request.form.get('field')` or `request.form['field']` to access text fields.

**Comment by DasIch** [comment]
"Works" and "Doesn't work" are not accurate descriptions for anything, especially without context. Please describe clearly what happens that you think shouldn't, what you think should happen instead and sufficient information - preferrably executable code - to reproduce the problem.

**Comment by untitaker** [comment]
If a checkbox is unticked, no form value and no key is sent.

**Comment by aliasm2k** [comment]
Hmm... Thanks @untitaker That sort of answers my question. :smiley:
