### ISSUE TITLE
persona example error 

### ISSUE THREAD

**Issue by rwdim** [mitsuhiko/flask#1310]
Out of the box, running the persona example, you get:

ImportError: No module named requests

Removing the import and replacing "requests" with "request" appears to resolve the issue.

**Comment by davidism** [comment]
Where is the "persona example"?  I searched the docs and didn't find anything.

**Comment by davidism** [comment]
You need to install the [requests](http://docs.python-requests.org/) library.

**Comment by kelvintaywl** [comment]
`requests` library and the `request` module from flask are two different things. you would need to `pip install requests`

**Comment by untitaker** [comment]
Not sure how "import request" would work, but it doesn't solve the issue. I added a note to the example.

**Comment by rwdim** [comment]
requests is not a part of the python distro, so it needs to be pip'd...

http://python-requests.org

**Comment by untitaker** [comment]
Yes, I added a note...
