### ISSUE TITLE
pylint errors on all example & template project

### ISSUE THREAD

**Issue by DavidHwu** [mitsuhiko/flask#1312]
Like to see flask examples follow good Python standards and pass pylint validation, especially with their examples people use for setup and reference.

Is there a reason why these don't follow the standard python package and and setups found in Pypi?
Here is an example:
https://pypi.python.org/pypi/python_boilerplate_template

Having looked at several other micro frameworks (ie. Pyramid, CherryPy, Pecan, etc)... they all seem to adopt these template patterns and work with pylint.

Here is a sample ...

-----------
(sandbox)Davids-MacBook-Pro-2:sandbox dhwu$ pylint --version
No config file found, using default configuration
pylint 1.4.0, 
astroid 1.3.2, common 0.63.2
Python 3.4.2 (default, Dec 18 2014, 08:45:34) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)]
(sandbox)Davids-MacBook-Pro-2:sandbox dhwu$ 

(sandbox)Davids-MacBook-Pro-2:sandbox dhwu$ pylint /Users/dhwu/eng/Flask-0.10.1/examples/blueprintexample 
No config file found, using default configuration
************* 
F:  1, 0: error while code parsing: Unable to load file '/Users/dhwu/eng/Flask-0.10.1/examples/blueprintexample/__init__.py' ([Errno 2] No such file or directory: '/Users/dhwu/eng/Flask-0.10.1/examples/blueprintexample/__init__.py') (parse-error)
(sandbox)Davids-MacBook-Pro-2:sandbox dhwu$ 

F:  1, 0: error while code parsing: Unable to load file '/Users/dhwu/eng/Flask-0.10.1/examples/flaskr/__init__.py' ([Errno 2] No such file or directory: '/Users/dhwu/eng/Flask-0.10.1/examples/flaskr/__init__.py') (parse-error)

**Comment by ThiefMaster** [comment]
Those are just very simple examples, not large applications. And for very small projects the single-python-file approach is quite common.

**Comment by DavidHwu** [comment]
Thanks... fwiw I love the nimble micro nature of flask!  
Even the template created by Flask doesn't pass pylint, and have very low scores.

As a python engineer who came from other web frameworks (large to micro).  They all pass pylint and have higher scores.  Just think this is something Flask can do more in the future.

I follow Jeff Knupp, and this blog details how he uses Flask and pylint together.  Presumably to resolve some of these issues along the way.
Ref: http://www.jeffknupp.com/blog/2013/11/15/supercharge-your-python-developers/

**Comment by untitaker** [comment]
I agree that Werkzeug and Flask should adopt both a linter and a stylechecker. I am unsure if pure pylint is a good option... I had very good with flake8 myself.

**Comment by jelmerdejong** [comment]
Would love to see this adopted. I'm learning Python and Flask and got recommended pylint to check my code and stay in the Python standards. However, all documentation and tutorial code fails, making it not easy :)

E.g.:

E:  4, 0: No name 'sqlalchemy' in module 'flask.ext' (no-name-in-module)
F:  4, 0: Unable to import 'flask.ext.sqlalchemy' (import-error)
C:  9, 0: Invalid constant name "app" (invalid-name)
C: 16, 0: Invalid constant name "db" (invalid-name)

J.

**Comment by untitaker** [comment]
**PyLint support is not going to happen.**

The things it tiries to check are not possible with static analysis in Python, yet pylint, instead of restricting itself to the things that *are* possible, simply does the wrong thing, complaining about broken imports just because it is unable to detect the magic behind Flask's extension import system. Supporting pylint effectively means restricting oneself to a limited subset of Python that is almost statically typed. Don't tell me these things are easily turned off: I might as well use a tool with defaults that are not completely surrealistic. Therefore:

**I agree that Flask and Werkzeug should adhere to a styleguide, including most of PEP8**. As said, I strongly like Flake 8, and I'd like to adopt it. I opened https://github.com/mitsuhiko/flask/issues/1329 for this.

**Comment by DavidHwu** [comment]
Understand pylint static issues mentioned earlier.  But I follow Google best practice and idiomatic Python author of using pylint.

It's found many bugs in team code prior, believe it's a good tool regardless of its shortcomings. Getting a good template or footing for new comers also sets IMHO right steps forward.
