### ISSUE TITLE
Flaskr tutorial Step 3 is missing content

### ISSUE THREAD

**Issue by TPMoyer** [mitsuhiko/flask#1314]
http://flask.pocoo.org/docs/0.10/tutorial/dbinit/
shows only the header and a portion of the first paragraph.

**Comment by untitaker** [comment]
Not for me. Could you provide a screenshot?

**Comment by TPMoyer** [comment]
Firefox 34.0.5 and IE 11.0.9600.17501  have the full page.
Chrome Version 39.0.2171.95 m 
shows the apostrophe in the fourth line of text, but nothing following.   The flask icon and the left column are also not displayed.    Screen shot is attached.
My system is Windows 7 pro 64bit service pack 1

![image](https://cloud.githubusercontent.com/assets/5302976/5726838/97a5ee76-9b2c-11e4-9430-d49389782b1b.png)

**Comment by untitaker** [comment]
Are you sure it's not some extension or proxy messing with the page?

**Comment by TPMoyer** [comment]
Same negative function after disabling all my chrome extensions.    Have not fiddled with proxy's, do not know how to check their state of being.

**Comment by untitaker** [comment]
I'm pretty sure it's a problem on your end. The server doesn't send any invalid headers.

Does this version work: http://flask.readthedocs.org/en/latest/

**Comment by TPMoyer** [comment]
Both the inital page from http://flask.readthedocs.org/en/latest/
and each of the subsequent pages all show full content.

**Comment by untitaker** [comment]
That's kinda weird, but since

- this doesn't seem to be an issue with Flask's doc server
- you now have a workaround for your issue

I'm going to close this issue. Please leave a note here if you ever find out what caused this issue.
