### ISSUE TITLE
flask.wrappers.Request.get_json fails to check for data

### ISSUE THREAD

**Issue by kenjones-cisco** [mitsuhiko/flask#1317]
If it is possible to provide optional data input as part of request, and content type is set to application/json, but no data was provided as it was optional, a call flask.request.json or flask.request.get_json will result in a BadRequest exception.

Instead of attempting to perform a json.loads on None or empty string, add at line 153:
`if not data:
    return None
`

I do realize there is a silent option, but that would seem to apply to situations when data was supplied but incorrectly formatted such that json was unable to load the data. Versus the situation where there is no data at all to even load.

I have also opened an issue with flask-restful (https://github.com/flask-restful/flask-restful/issues/387) as well to change how or when the call to get_json happens, always pass silent=True, or provide consumers an option to pass through the option silent=True. 

But it seems cleaner to check for the existence of data prior to trying to process the data.

**Comment by RonnyPfannschmidt** [comment]
in my oppinion a bad request is correct, since 'no data' is not valid json, so the request is 'bad'

**Comment by ThiefMaster** [comment]
agreed, "optional data" in an API expecting JSON should be `null` or `[]` or `{} depending on what the API usually expects. ..

**Comment by untitaker** [comment]
I agree with @RonnyPfannschmidt and @ThiefMaster. I don't consider this to be a good kind of HTTP API, but if you really want this, it should be explicitly done in the application.

However, I'm not really opposed to raising different subclasses of BadRequest to distinguish between types of json parsing errors.

**Comment by DasIch** [comment]
Meh. `.get_json()` shouldn't fail silently but failing with a `BadRequest` is bad just as it is obviously bad for `request.form[]` to do so. Nevertheless being consistently bad is better than being inconsistently bad.

In the long term we should consider to never raise a `BadRequest` on a framework level. A 400 is rarely the response that one wants to return and even if it is, such a response should include information an end-user can act on. This can only be provided by applications.

**Comment by untitaker** [comment]
IMO the BadRequest on request.form is useful. In any case we should provide consistency, yes.

**Comment by ThiefMaster** [comment]
Agreed, for the request dicks it's quite useful. Missing form data is a 
valid case for a 400.

**Comment by RonnyPfannschmidt** [comment]
@DasIch i think bad request is completely valid in all those cases,

however i think in debug mode it should provide a json object describing the problem

something like `{"error": "Json body invalid"}`
or `{"error": "key missing", "attr": "form", "key": "something"}`
maybe a general debuggable bad request might be a good idea

**Comment by untitaker** [comment]
Probably should be displayed in the console, putting it into the response body doesn't work out well if the user has errorhandlers for 400.

**Comment by crazygit** [comment]
Met the same 'bug', agreed with @kenjones-cisco , Maybe provide optional data input as part of request is good

**Comment by untitaker** [comment]
JFTR if anybody wants to fix this: Assuming any kind of default value if the client didn't send any data is definetly not going to fly. However, sensible changes include logging something to the console in debug mode (not to the one in the browser).

Really, most changes are fine as long as they are unlikely to change existing behavior in production apps.

**Comment by keyanp** [comment]
So seeing as we want to maintain existing behavior, I think the most useful change would be extending a subclass of BadRequest which alerts the user that the error is due to an empty data argument.

Unless someone disagrees with that approach, I'll replicate the error and work on it this week.

**Comment by untitaker** [comment]
I think there is a subclass called BadRequestKeyError, but since all of this logic is part of Werkzeug, I'm unsure if you'll be successful with that approach. Definetly give it a try though!

**Comment by keyanp** [comment]
After looking at this some more I think that the current behavior makes sense. Extending a subclass of BadRequest would involve modifying Werkzeug, which would certainly change the current behavior of other code as well. I'm not completely sure if there is other code that sends messages to the logger but I couldn't find this being done anywhere in the codebase. Instead I think this sort of error should just be handled in the application logic. Regardless I added the error content to the client response, perhaps this would simplify debugging.

**Comment by untitaker** [comment]
Your fix looks pretty good, but I fear that it might reveal *too much* information in production mode.

**Comment by RonnyPfannschmidt** [comment]
is that error handling code invoked anywhere other than parsing json from the client?

maybe make the additional data dependent from the value of DEBUG ?

**Comment by keyanp** [comment]
@RonnyPfannschmidt No, line 161 is the only time that the `on_json_loading_failed` error is invoked.

Could you elaborate on the DEBUG value? I'm assuming you mean the app config DEBUG, but how do you refer to an app specific config variable inside of the more general `wrappers.py` module?

**Comment by untitaker** [comment]
`flask.current_app` should be usable at response time.

**Comment by untitaker** [comment]
That said, we probably need fallback code for the case where it isn't.

**Comment by keyanp** [comment]
So how about just branching? If the current app if in DEBUG mode then we add the exception content to the response, otherwise we just return the standard 400 message as we are now. If it sounds good I can add that.

**Comment by RonnyPfannschmidt** [comment]
thats what i meant

**Comment by keyanp** [comment]
`current_app` worked well, I changed the message to be conditional on DEBUG mode, see #1360

**Comment by untitaker** [comment]
Usability issues fixed by https://github.com/mitsuhiko/flask/pull/1360, but overall behavior not changed.

**Comment by TechBK** [comment]
sorry, i think that: If i want control TYPE of except, Request.get_json() should raise errors.
