### ISSUE TITLE
test_client removes query_string

### ISSUE THREAD

**Issue by flaker** [mitsuhiko/flask#1324]
I've been trying to use test_client with some simple services I've made but noticed that when calling a service sending something through the query string, nothing is received on the endpoint. So:

test_client.get("http://localhost/api1_0/some-service?param1=value1")

(Actually I use url_to())

gets to some-service as expected, but the request.args collection is empty. This call works perfectly if I use an external tool like curl.

Debugging, I've got to the method make_test_environ_builder (testing.py) where url.path is used but url.querystring is just disregarded. 

In the end, I've found a workaround (while writing this issue):

test_client.get("http://localhost/api1_0/some-service", query_string = "param1=value1")

The added parameter travels to the EnvironBuilder.

It seems to me that this is a bug since there is no reason why the query string should be disregarded in the first place. But I am new to Flask so I may be missing something

Thank you.

**Comment by untitaker** [comment]
Could you try with the dev-version of Werkzeug?

    pip install git+https://github.com/mitsuhiko/werkzeug.git

**Comment by untitaker** [comment]
Or it might also be because you use an old version of Werkzeug...

**Comment by untitaker** [comment]
@flaker Any update on this? Otherwise I'll close this issue.

**Comment by flaker** [comment]
Hi @untitaker ,

To answer your  previous comment. I am using Werkzeug 0.9.6 on my Flask setup, I believe that is a rather new version.

I am going to test getting from git and go back to you on that in a couple of minutes.

**Comment by flaker** [comment]
Ok,

This is the script I used to test the issue. I am copying it because maybe it is not even a bug, just my ignorance on Flask.

```python
from flask import Flask, request, url_for

app = Flask(__name__)
app.config["SERVER_NAME"] = "localhost"

@app.route("/srv")
def srv():
    flag = request.args.get("hello")
    if flag != "True":
        return "Bye world"
    return "Hello world"

if __name__ == "__main__":
    app_context = app.app_context()
    app_context.push()
    query_string_param = "hello=True"
   
    client = app.test_client()
    base_url = url_for("srv") 
    url_with_param = base_url + "?" + query_string_param
    print "Target Url is: %s" %url_with_param
    print client.get(url_with_param).get_data()
    print client.get(base_url, query_string=query_string_param).get_data()
```
I understand that the correct output should be:

```
Target Url is: http://localhost/srv?hello=True
Hello world
Hello world
```

but instead it is:
```
Target Url is: http://localhost/srv?hello=True
Bye world
Hello world
```

The exact same output is reproduced used the following (output from `pip freeze`):

```
Flask==0.10.1
itsdangerous==0.24
Jinja2==2.7.3
MarkupSafe==0.23
Werkzeug==0.9.6
```
and the version with Wekzeug downloaded from git
```
Flask==0.10.1
itsdangerous==0.24
Jinja2==2.7.3
MarkupSafe==0.23
## FIXME: could not find svn URL in dependency_links for this package:
Werkzeug===0.10.dev0dev-20150125
```

**Comment by flaker** [comment]
I've just found this. 

A change on the method I mentioned (`make_test_environ_builder `) seems to have fixed the issue.

https://github.com/mitsuhiko/flask/blob/b81f72070ec0dc2bede09eedea3d0b0360887720/flask/testing.py

**Comment by untitaker** [comment]
Ok so this is fixed in development?

**Comment by flaker** [comment]
I've installed:
pip install git+https://github.com/mitsuhiko/flask.git

and the issue is fixed there.

Thank you @untitaker  sorry for bothering you with a solved issue.

**Comment by untitaker** [comment]
No problem, it's been a while since we released a new version.

**Comment by sibeliusseraphini** [comment]
is this on 0.10.1?

**Comment by untitaker** [comment]
https://github.com/pallets/flask/commit/e7c587789ae22a626196cea26340253dd9b70bf1 seems to be in 0.10-maintenance, so 0.10.2 will contain it.
