### ISSUE TITLE
Strange behaviour in app.route decorator 'methods' parameter when using string

### ISSUE THREAD

**Issue by entd** [mitsuhiko/flask#1328]
```python
app = Flask(__name__)

@app.route('/')
def form():
    return render_template('form_submit.html')
@app.route('/hello/', methods=('POST'))
def hello():
    name=request.form['yourname']
    email=request.form['youremail']
    return render_template('form_action.html', name=name, email=email)

# Run the app :)
if __name__ == '__main__':
  app.run( 
        host="0.0.0.0",
        port=int("7777")
  )
```
While tupple is iterable for flask accept this without any error warning or problem: even more: ("GET", "POST") works as well as ["GET", "POST"].
However with single element string there is problem:
```python
import requests
r = requests.post("http://127.0.0.1:7777/hello")
print("Status code: {}".format(str(r.status_code)))
print("Headers: {}".format(r.headers))
```
Output:
``` python
Status code: 405
Headers:  {'Allow': 'O, OPTIONS, T, P, S', 'Date': 'Wed, 28 Jan 2015 07:38:05 GMT', 'Content-Type': 'text/html', 'Server': 'Werkzeug/0.9.6 Python/3.4.2', 'Content-Length': '178'}
```
Seems that flask happily parses (("POST")) letter by letter. Posting with curl using method "P"  is valid thing in flask.
While it is stupid use case, I doubt that Flask should happily churn  String letter by letter. Also I think that after possible fix it would be easy to unit test :smirk: I think even for custom method definition this is not a valid or good behaviour.

**Comment by ThiefMaster** [comment]
('foo') doesn't create a tuple, `('foo',)` does. So you were passing a plain string instead of a tuple.

**Comment by entd** [comment]
OK I understood, my bad I fixed report to reflect that it is string problem

**Comment by ThiefMaster** [comment]
Maybe it would make sense to either fail when a string is passed or convert it to a single-element tuple.

**Comment by entd** [comment]
Sorry, my bad. I edited it a bit. I agree with ThiefMaster it would make more sense to convert it to tuple or handle as whole string, failing, instead sillently iterating over its letters.

**Comment by untitaker** [comment]
I agree that there should be an error message. @entd would you like to write such a patch?

**Comment by entd** [comment]
I would like to.

**Comment by untitaker** [comment]
Great! Mail me on the address linked to my profile if you need any help.

**Comment by mhavard999** [comment]
@entd must be using an older version of flask.  In the current version you get a TypeError if you try to do what he did above.  The server will not even start.  Commit where it was fixed:
https://github.com/mitsuhiko/flask/commit/af5a0853bfe36d547af93b904729a43fcf8cc55d?diff=unified

**Comment by untitaker** [comment]
Oh ok, that was quite a long time ago.

**Comment by entd** [comment]
No I am not. I am using newest version from pypy on python3. Maybe that is the problem.

**Comment by entd** [comment]
Oh sorry that is indeed old version problem stable release was made before that commit. Seems that maybe you need to release new stable version and bump number up :)

**Comment by untitaker** [comment]
Ok, it is fixed now though in either case.
