### ISSUE TITLE
Method is_json does not support capital letters in mimetype

### ISSUE THREAD

**Issue by KarelJakubec** [mitsuhiko/flask#1330]
Method is_json (flask/wrappers.py:112) tests whether mimetype is in format 'application/...+json'. According to http://tools.ietf.org/html/rfc2045, mime types are case insensitive.

'The type, subtype, and parameter names are not case sensitive.  For example, TEXT, Text, and TeXt are all equivalent top-level media types.'
 
So mimetype 'ApLiCaTiOn/jSoN' is technically fine (and yes, extremely rare) and as the method tests the mimetype just for lowercase mimetype 'application/json' the previous example will fail, yet it should be ok.

**Comment by untitaker** [comment]
This is a bug in Werkzeug I believe, not Flask.

**Comment by KarelJakubec** [comment]
The question is what Werkzeug should do with it? Convert it all to lower/upper case? The RFC is funny as additional parameter values MAY be case sensitive (like charset=UTF-8 is something different as charset=utf-8), which means that Werkzeug may convert mimetype and parameter names, but it cannot convert parameter values. :) And the decision whether it is a json or not is done in Flask.

Anyway, the fix is pretty simple I believe.

**Comment by untitaker** [comment]
I think Werkzeug should read and process values in a case-insensitive way, but always guarantee that its output will be lowercase.

**Comment by KarelJakubec** [comment]
Ok, I'll file new issue/feature request in Werkzeug. 

However I believe that the opinion there will be that it is not a Wekrzeug's job to convert header values and it is a user who should deal with it. :)

**Comment by untitaker** [comment]
I also maintain Werkzeug :)
