### ISSUE TITLE
Error 404 for linked flask-docs.zip

### ISSUE THREAD

**Issue by hartwork** [mitsuhiko/flask#1333]
At
http://flask.pocoo.org/
there is a link "zipped HTML" to
http://flask.pocoo.org/docs/flask-docs.zip
giving 404.

Please fix :)

**Comment by davidism** [comment]
Duplicate of pocoo/metaflask#7 and [numerous previous reports](https://github.com/mitsuhiko/flask/issues?q=is%3Aissue+is%3Aopen+docs).

Please search :(

**Comment by ramonsaraiva** [comment]
hartwork,

Clone the flask repository, and build the docs with python sphinx.
You can build them to HTML using the argument `-b HTML`.

I think that's the easier way to get your offline flask docs :)

**Comment by hartwork** [comment]
Thanks! It would still be cool to have the website link fixed :)
