### ISSUE TITLE
Typo on flask.g documentation section

### ISSUE THREAD

**Issue by michaelamie** [mitsuhiko/flask#1334]
Where: http://flask.pocoo.org/docs/0.10/api/#flask.g

"On top of that it will delegate access to the current application’s JSOn encoders and decoders for easier customization."

Should be JSON not JSOn, right?

**Comment by untitaker** [comment]
Yeah... patches welcome. :)

**Comment by michaelamie** [comment]
Sure, can you point me in the direction to do so? Is it in a repo? Sorry, I was trying to find it on my own but I didn't run across it.

**Comment by untitaker** [comment]
Hmm, okay. Then this will fix itself when the next version is released.

**Comment by michaelamie** [comment]
Awesome! Thanks. 🍻
