### ISSUE TITLE
Snippets - Decorators: Verify a Google authentication token

### ISSUE THREAD

**Issue by hperello** [mitsuhiko/flask#1340]
In snippets -> decorators -> Verify a Google authentication token
I would change:

                           headers={'Host': 'www.googleapis.com',
                                    'Authorization': access_token})

to:

                           headers={'Host': 'www.googleapis.com',
                                   'Authorization': 'Bearer '+access_token
                           })

You can try in https://developers.google.com/oauthplayground/

**Comment by untitaker** [comment]
Please file against https://github.com/pocoo/flask-snippets

**Comment by hperello** [comment]
sorry, I can't find this snippet there

**Comment by untitaker** [comment]
We haven't actually migrated to the repo yet, but I think issues don't get as lost there.

**Comment by untitaker** [comment]
Just open an issue on the repo for now.

**Comment by hperello** [comment]
Ok, thanks you, I moved it there.
