### ISSUE TITLE
It's been almost 2 years since the last major update.. is there any realistic date for any new release?

### ISSUE THREAD

**Issue by lipis** [mitsuhiko/flask#1344]

**Comment by untitaker** [comment]
The next release is going to be 1.0, and that takes quite a lot of effort.

**Comment by lipis** [comment]
![screen shot 2015-03-11 at 10 46 29](https://cloud.githubusercontent.com/assets/125676/6593787/c1b4f62c-c7db-11e4-8c7b-847a4bcdc857.png)

**Comment by abdelouahabb** [comment]
I think it is time to name it 1.0 because it became the defacto in python world, now, even hosting PaaS are giving examples by using Flask and not Django, so time to give him some credit ;)

**Comment by klinkin** [comment]
+1

**Comment by lipis** [comment]
One month before the 2 years mark since the last release.. :)

Yes I understand that is a lot of work.. but still.. How soon is the very soon @mitsuhiko?

**Comment by lipis** [comment]
Shall we expect anything for this year?!
