### ISSUE TITLE
flask.send_file gives bad security advice

### ISSUE THREAD

**Issue by ezyang** [mitsuhiko/flask#1345]
On http://flask.pocoo.org/docs/latest/api/#flask.send_file the following is suggested:

> Please never pass filenames to this function from user sources without checking them first. Something like this is usually sufficient to avoid security problems:

>     if '..' in filename or filename.startswith('/'):
           abort(404)

This is *terrible* advice. It would be much better to tell people that if they want to pass in filenames, they should use http://flask.pocoo.org/docs/latest/api/#flask.send_from_directory instead.

**Comment by untitaker** [comment]
I completely agree with you. This seems to be for historic reasons, apparently ``send_from_directory`` has been added in later versions. So, patches welcome :)

**Comment by ezyang** [comment]
https://github.com/mitsuhiko/flask/pull/1346
