### ISSUE TITLE
Import redirection makes it difficult to catch exceptions

### ISSUE THREAD

**Issue by jfinkels** [mitsuhiko/flask#1347]
See https://github.com/graup/flask-restless/blob/post-excluding-id/tests/test_manager.py#L568. Here we are trying to catch an exception using the `nose.tools.raises` decorator. On Python 3, we seem to be running into an issue with Flask's extension import redirect.

The issue is that when the exception gets raised (in https://github.com/graup/flask-restless/blob/post-excluding-id/flask_restless/manager.py#L484), it gets raised as an instance of `flask_restless.manager.IllegalArgumentError`, not as an instance of `flask.ext.restless.manager.IllegalArgumentError`. This can be verified by the code below (if you have the source code for Flask-Restless available in your current working directory):

    >>> from flask.ext.restless.manager import IllegalArgumentError as E1
    >>> from flask_restless.manager import IllegalArgumentError as E2
    >>> E1
    <class 'flask.ext.restless.manager.IllegalArgumentError'>
    >>> E2
    <class 'flask_restless.manager.IllegalArgumentError'>
    >>> E1 is E2
    False

Now when nose tries to check for a raised instance of `flask.ext.restless.manager.IllegalArgumentError`, it doesn't find one, because the raised exception is really an instance of `flask_restless.manager.IllegalArgumentError`. What I would expect to happen is that `E1 is E2`.

**Comment by jfinkels** [comment]
Oh, it actually seems that this is only an issue if I import from the more specific package `flask.ext.restless.manager` instead of importing from `flask.ext.restless`. If I make the exception available at the top level package of my extension, this is no longer a problem. I'm not sure if this could still be considered an issue, in that case...

**Comment by untitaker** [comment]
I am not sure if this is worth fixing. The magical ext package will be removed in 1.0

**Comment by keyanp** [comment]
Looks like @jfinkels has changed their code to allow for catching the exception. I'm suggesting this be closed as it is a niche problem that has a workaround and will not be an issue once the `ext` import magic is removed.
