### ISSUE TITLE
Problem running Flask with an ssl_context under Werkzeug 0.10.1

### ISSUE THREAD

**Issue by Cabu** [mitsuhiko/flask#1352]
With the last Werkzeug (0.10.1) I get the following error message:

	Exception in thread Thread-1:
	Traceback (most recent call last):
	  File "C:\PGM\Python27\lib\threading.py", line 810, in __bootstrap_inner
		self.run()
	  File "C:\PGM\Python27\lib\threading.py", line 763, in run
		self.__target(*self.__args, **self.__kwargs)
	  File "C:\PGM\Python27\lib\site-packages\werkzeug\serving.py", line 602, in inner
		passthrough_errors, ssl_context).serve_forever()
	  File "C:\PGM\Python27\lib\site-packages\werkzeug\serving.py", line 506, in make_server
		passthrough_errors, ssl_context)
	  File "C:\PGM\Python27\lib\site-packages\werkzeug\serving.py", line 450, in __init__
		self.socket = ssl_context.wrap_socket(self.socket,
	AttributeError: 'Context' object has no attribute 'wrap_socket'

Reverting to Werkzeug 0.9.6 make it work again like a charm.

**Comment by untitaker** [comment]
Which code do you use? Which Python version do you use?

**Comment by Cabu** [comment]
I use Python 2.7 for win32
As for code I suppose you mean version of Flask. Then it is the last available on PIP (Flask 0.10.1)

**Comment by untitaker** [comment]
No, the code of a Flask app that replicates this problem.

**Comment by ThiefMaster** [comment]
Also, please mark your traebacks as code (put triple-backtick fences in the line right before and right after the code) so they are formatted properly.

**Comment by Cabu** [comment]
My code is of the following form:

    .... other imports
    from OpenSSL import SSL

    .... my app code

    if __name__ == "__main__":
        app = Flask(__name__)
        .... some more inits (db, mail, compress, login...)

        context = SSL.Context(SSL.TLSv1_2_METHOD)
        context.use_privatekey_file(app.config['PRIVATE_KEY_FILE'])
        context.use_certificate_file(app.config['CERTIFICATE_FILE'])

        app.run(debug=True, ssl_context=context)

**Comment by untitaker** [comment]
Ah yes, OpenSSL contexts have been discontinued in favor of using Pythons' [stdlib ``SSLContext``](https://docs.python.org/2/library/ssl.html#ssl.SSLContext). It is easier to support across Python versions.

**Comment by Cabu** [comment]
Hum... Then perhaps pip should not have let me install that version due to incompatibility with python...

**Comment by untitaker** [comment]
Which Python version are you using then? How is this a pip issue?

**Comment by Cabu** [comment]
I use Python 2.7.8 win32. 
Why a PIP issue? Because as PIP check for library version dependency, it should check for Python version dependency too. I did get this problem trying to update Flask (who was up to date) but it updated Werkzeug. It should have know that this version of Werkzeug would not work with my Python version or at least warned me of some possible incompatibilities...

**Comment by ThiefMaster** [comment]
SSL **in the dev server** is the only thing that requires 2.7.9 - so I don't think it would make lots of sense to *require* that version.

**Comment by untitaker** [comment]
Not even that, only if you want to use the SSLContext class.
