### ISSUE TITLE
Reload takes > 60 seconds

### ISSUE THREAD

**Issue by dmitrybelyakov** [mitsuhiko/flask#1353]
Hi everyone!

Since I updated werkzeug to 0.10.1 this morning reloader stopped working. Is any specific configuration required besides installing watchdog?

I run with:

```python
run_simple(
        hostname='0.0.0.0',
        port=5000,
        application=app,
        use_reloader=True,
        use_debugger=True,
        reloader_type='watchdog'
    )

# * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
# * Restarting with inotify reloader
```
I'm under vagrant and tried both with and without NFS to no success.

**Comment by dmitrybelyakov** [comment]
Ok, I did some research and can say that reload is actually happening. The thing is it watchdog-reload won't work under vagrant, virtualbox, and probably docker as well. This is not the reloader's fault, just how the underlying inotify works.

For reload to work under guest os you need to use stat reloader. It actually takes about 90 seconds to do a single reload with stat reloader. That is for us and our project. The exact time will depend on the number of files in your project.

There is this pull request mitsuhiko/werkzeug#669 that will allow you to regulate what files are being watched. Not yet on PyPi though.

Right now we are rolling or own reload solution will [poke](https://github.com/projectshift/poke).

**Comment by untitaker** [comment]
Please continue in https://github.com/mitsuhiko/werkzeug/issues/682, we did some major changes to the reloader which could have caused serious regressions.
