### ISSUE TITLE
Documentation PDF 404's on flask site

### ISSUE THREAD

**Issue by davidthewatson** [mitsuhiko/flask#1356]
This link:

http://flask.pocoo.org/docs/flask-docs.pdf

on this page:

http://flask.pocoo.org/

Generates a 404.

**Comment by davidism** [comment]
Duplicate of pocoo/metaflask#7 and [all these](https://github.com/mitsuhiko/flask/issues?q=is%3Aissue+is%3Aopen+documentation).

**Comment by pythonui** [comment]
When its get fixed? Flask users really need this.... :)
