### ISSUE TITLE
Flask Roadmap

### ISSUE THREAD

**Issue by pythonui** [mitsuhiko/flask#1362]
What about Flask 1.0 roadmap?

**Comment by keyanp** [comment]
This isn't very descriptive, what do you mean? If you just mean things that need to be done before 1.0, then just select 1.0 under the milestones tab in the issue tracker.

**Comment by untitaker** [comment]
Yeah that's what we have for now. We also don't have a real roadmap because of a lack of resources.

**Comment by pythonui** [comment]
@keyanp Yes... Thanks

**Comment by pythonui** [comment]
@untitaker What types of resources?

**Comment by hbrls** [comment]
@pythonui Mythical Man-Month, I think ;)

**Comment by untitaker** [comment]
That's a pretty relevant book, basically we're lacking people who are interested in long-term involvement, something less casual.

**Comment by bushig** [comment]
To have someone involved there should be some roadmap/TODO-list, so people can see if they are able or intrested in implemending such features.
