### ISSUE TITLE
before_render_template signal

### ISSUE THREAD

**Issue by ThiefMaster** [mitsuhiko/flask#1370]
This signal would receive the name of the template and the context and would be able to modify the context before the template is actually rendered. It could even go one step further and use the return value from the signal instead of rendering the template if it's not None.

**Comment by jirikuncar** [comment]
I like the idea and it would allow us to remove our [custom registration of template context processors](https://github.com/inveniosoftware/invenio/blob/master/invenio/ext/template/context_processor.py).

**Comment by ThiefMaster** [comment]
That looks like lots of black magic which could go away ;)
