### ISSUE TITLE
When debug mode is enabled, control-c takes forever to quit, and reloads are slow.

### ISSUE THREAD

**Issue by spideynn** [mitsuhiko/flask#1373]
When I do control-c in the Python Console, it either takes a minute, or doesn't do anything.
Also, when I make a change to the file and save it, it takes a while to reload the file as well.
Running Python 3.4, Windows 8.1. Running in the [Spyder IDE](https://github.com/spyder-ide/spyder) Python Console.

Edit: This also happens in the regular python console.
Edit 2: It seems that Control-C takes effect when the file reloads...

**Comment by keyanp** [comment]
Is the reloader working for you at all? Could this be related to #1355 and #1353?

**Comment by spideynn** [comment]
The reloader works, it just takes some time until it actually reloads. Its also weird that Control-C doesn't do anything until it reloads.

**Comment by keyanp** [comment]
Can you include a gist of the code that is causing the problem?

**Comment by spideynn** [comment]
https://github.com/spideynn/BlazeGoat-Panel/blob/master/app.py

**Comment by spideynn** [comment]
This also seems to be related to #1353 when I looked into this further.

**Comment by untitaker** [comment]
This is the same as https://github.com/mitsuhiko/werkzeug/issues/682, please follow the instructions there!

**Comment by spideynn** [comment]
Just to mention this, I'm still having issues where Control-C doesn't take effect until the next reload even with Watchdog installed with pip.

**Comment by untitaker** [comment]
Ah ok, I refiled that as https://github.com/mitsuhiko/werkzeug/issues/711
