### ISSUE TITLE
documentation PDF link is dead

### ISSUE THREAD

**Issue by introvertmac** [mitsuhiko/flask#1375]
got 404 for "download document as PDF"

**Comment by ThiefMaster** [comment]
Duplicate of pocoo/metaflask#7

**Comment by charleswhchan** [comment]
(Reminder before closing this ticket) 
Similar issue with "zipped HTML"

**Comment by keyan** [comment]
@charleswhchan I am aware: #1300, #1333

**Comment by kierdwyn** [comment]
Try this link for a PDF version documentation:
https://media.readthedocs.org/pdf/flask/latest/flask.pdf

**Comment by charleswhchan** [comment]
Thanks @kierdwyn.

... now we just need to update the link in the welcome doc:
http://flask.pocoo.org/
