### ISSUE TITLE
CPU usage increase when debug=True running by virtualenv

### ISSUE THREAD

**Issue by coolcoca** [mitsuhiko/flask#1377]
When I running a flask app with debug=True in virtualenv, the cpu usage increase to 20%. But if I set debug=False, the cpu usage is only 1%.
If I running without virtualenv, all is ok.

**Comment by davidism** [comment]
Install the `watchdog` package when using the reloader, the built-in watcher is inefficient.

http://stackoverflow.com/questions/28241989/flask-app-restarting-with-stat/28242285#28242285

**Comment by coolcoca** [comment]
fixed thank you.

**Comment by untitaker** [comment]
Duplicate of https://github.com/mitsuhiko/werkzeug/issues/682
