### ISSUE TITLE
Flask Request Signal - Workflow

### ISSUE THREAD

**Issue by rturk** [mitsuhiko/flask#1382]
Please comment if the attached workflow is a correct description of how Flak handles an request and when and how signals are triggered

I'm particularly interested in the request_tearing_down signal. I want to log requests (user page views) to a database, but I don't want to compromise the client experience regarding speed. So I would like to only log the request data to a DB after the data was successfully sent to the client

![flask signals](https://cloud.githubusercontent.com/assets/2236950/6657010/363efcde-cb1c-11e4-8d12-2b70d72fa59b.png)

**Comment by untitaker** [comment]
Please use StackOverflow or IRC for support.

**Comment by rturk** [comment]
Created StackOverflow question at http://stackoverflow.com/questions/29064764/flask-request-signal-request-tearing-down-workflow

**Comment by hbrls** [comment]
@untitaker Do you have a chart like that to explain?
