### ISSUE TITLE
form.hidden_tag() not XHTML 1.1-compliant

### ISSUE THREAD

**Issue by nvitucci** [mitsuhiko/flask#1386]
Using form.hidden_tag() results in an element like the following:

<div style="display:none;"><input id="csrf_token" name="csrf_token" type="hidden" value="..."></div>

which is not compliant with the XHTML 1.1 standard as the "input" element is not closed.

**Comment by davidism** [comment]
This is a WTForms issue, it is not related to Flask or Flask-WTForms.  Report it on the WTForms issue tracker: https://github.com/wtforms/wtforms/issues.
