### ISSUE TITLE
Flask doesn't support resume download to client (no HTTP byte-range support) in 'static' folder

### ISSUE THREAD

**Issue by dns** [mitsuhiko/flask#1388]
app = Flask(__name__, static_folder='static', static_url_path='')

I've tested this, currently Flask seems doesn't support resuming download when serving static files in "static" directory. 
This feature is very useful if the client (browser/download manager) requested very large files.

**Comment by ThiefMaster** [comment]
You should let the webserver handle file delivery by using `X-Sendfile`: http://flask.pocoo.org/docs/0.10/api/#flask.Flask.use_x_sendfile

**Comment by supersaeyan** [comment]
I am using heroku PAAS environment to serve static files. How do i serve multithreaded and resumable file downloads ?

**Comment by jeffwidman** [comment]
@supersaeyan the issue tracker is for bug reports & feature requests. Questions are better posted to StackOverflow or the Flask mailing list.

**Comment by supersaeyan** [comment]
Thanks for the info
