### ISSUE TITLE
Flask mailing list not accepting my messages

### ISSUE THREAD

**Issue by dunpealer** [mitsuhiko/flask#1396]
Over the past 2 months I've sent 3 questions to the mailing 	flask@librelist.com mailing list. It had worked for me before, The questions have been completely ignored, and they don't even appear in the archive.

I've sent another question earlier, in mid December 2014, and it was archived and responded to. The 3 questions since then have not.

**Comment by keyan** [comment]
Hi @dunpealer, could you possibly re-send your last question just so I can see what happens?

**Comment by dunpealer** [comment]
@keyan: just re-sent the question per your request. It was originally sent 4 hours ago.

**Comment by untitaker** [comment]
The Flask mailinglist is known to be broken quite some time now: https://github.com/pocoo/metaflask/issues/60

The problem boils down to finding a suitable alternative to librelist.

**Comment by untitaker** [comment]
I'll leave this open though because the metaflask repo doesn't get much visibility.

**Comment by keyan** [comment]
I don't think we need 3 copies of the same issue: #682, #666, and #1396 are basically the same. I think I'd like to close #666 and #1396.

**Comment by untitaker** [comment]
Please go ahead.
