### ISSUE TITLE
flask.Request should have an is_static field for content served from the static folder

### ISSUE THREAD

**Issue by zippy1981** [mitsuhiko/flask#1397]
It would be nice to be able to easily tell static content served from flask is static in a before_request for example.

**Comment by ThiefMaster** [comment]
What's wrong with testing `request.endpoint == 'static'`?

**Comment by davidism** [comment]
`request.endpoint and request.endpoint.split('.')[-1] == 'static'` if you want to account for paths that didn't match an endpoint and blueprint static routes.  So slightly more complicated.  It also assumes we know that those are the static routes, and that other routes are not sending static files.

**Comment by zippy1981** [comment]
Yes I did that. I was being stupid.
