### ISSUE TITLE
Knowing if the App started

### ISSUE THREAD

**Issue by Martin-Spamer** [mitsuhiko/flask#1411]
The suggested way to start the app from http://flask.pocoo.org/docs/0.10/quickstart/#a-minimal-application is app.run(...).  Examining the source code of run, which chains run_simple it appears there is now way to detect success or failure.

Perhaps the run method should return a status (True/False) or (self/None)

**Comment by untitaker** [comment]
The run method is blocking and will raise an exception if it fails.
