### ISSUE TITLE
OperationalError: no such table: entries

### ISSUE THREAD

**Issue by dayiguizhen** [mitsuhiko/flask#1417]
I am learning flask framework and want to set up flaskr by following the flask tutorial. In the end I am getting the error:OperationalError: no such table: entries.

the code of flaskr.py is here below

    import os
    from sqlite3 import dbapi2 as sqlite3
    from flask import Flask, request, session, g, redirect, url_for, abort, render_template, flash

    app = Flask(__name__);

    app.config.update(dict(
        DATABASE=os.path.join(app.root_path,'flaskr.db'),
        DEBUG=True,
        SECRET_KEY='development key',
        USERNAME='admin',
        PASSWORD='default'
        ))

    app.config.from_envvar('FLASK_SETTINGS',silent=True);

    def connect_db():
        """Connects to the specific database."""
        rv = sqlite3.connect(app.config['DATABASE']);
        rv.row_factory = sqlite3.Row;
        return rv;

    def init_db():
        db = get_db();
        with app.open_resource('schema.sql',mode='r') as f:
            db.cursor().executescript(f.read());
        db.commit();

    @app.cli.command('initdb')
    def initdb_command():
        init_db();
        print('Initialized the database.');

    def get_db():
        if not hasattr(g,'sqlite_db'):
            g.sqlite_db = connect_db();
        return g.sqlite_db;

    @app.teardown_appcontext
    def close_db(error):
        if hasattr(g,'sqlite_db'):
            g.sqlite_db.close();

    @app.route('/')
    def show_entries():
        db = get_db();
        cur = db.execute('select title, text from entries order by id desc');
        entries = cur.fetchall();
        return render_template('show_entries.html', entries=entries);

    @app.route('/add',methods=['POST'])
    def add_entry():
        if not session.get('logged_in'):
            abort(401);
        db = get_db();
        db.execute('insert into entries (title, text) value (?, ?)',[request.form['title'],request.form['text']]);
        db.commit();
        flash('New entry was succeedfully posted');
        return redirect(url_for('show_entries'));

    @app.route('/login',methods=['GET','POST'])
    def login():
        error = None;
        if request.methods == 'POST':
            if request.form['username'] != app.config['USERNAME']:
                error = 'Invalid username';
            elif request.form['password'] != app.config['PASSWORD']:
                error = 'Invalid password';
            else:
                session['logged_in'] = True;
                flash('You were logged in');
                return redirect(url_for('show_entries'));
        return render_template('login.html',error=error);

    @app.route('/logout')
    def logout():
        session.pop('logged_in',None);
        flash('You were logged out');
        return redirect(url_for('show_entries'));

    if __name__ == '__main__':
        app.run(host='0.0.0.0',debug=True);

**Comment by untitaker** [comment]
You need to run the `initdb` command.

**Comment by dayiguizhen** [comment]
I try to run init_db() but there is getting another error:RuntimeError: Working outside of application context.

it also show me some message:
This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().

**Comment by dayiguizhen** [comment]
I add the app.app_context() in the code

def init_db():
	with app.app_context():
		db = get_db();
	with app.open_resource('schema.sql',mode='r') as f:
		db.cursor().executescript(f.read());
		db.commit();


and now the error is sqlite3.ProgrammingError: Cannot operate on a closed database

**Comment by untitaker** [comment]
Did you try the `sqlite` command at http://flask.pocoo.org/docs/0.10/tutorial/dbinit/#step-3-creating-the-database ?

**Comment by dayiguizhen** [comment]
Now I can succeed build flaskr and visit it on browser.
Because I have commented the line below:

def close_db(error):
	print("CLOSED");
	if hasattr(g,'sqlite_db'):
		print("NO!")
                //comment this line:
		#g.sqlite_db.close();

But I can't understand why this function be used.

**Comment by untitaker** [comment]
Please use four spaces to mark code as such. Will take a look.

**Comment by untitaker** [comment]
You shouldn't call `db.close()` in the endpoint function, this is done in the teardown handler.

Please don't use the issuetracker for support requests.
