### ISSUE TITLE
Flask reloader adds stdout buffering when used with supervisord

### ISSUE THREAD

**Issue by hamiltont** [mitsuhiko/flask#1420]
Sorry for long report, this took a while to debug. I'm not an expert on how reloading works, so hopefully someone can explain what is happening. This only happens when I use Flask's reload while launching flask using supervisord, so if it ends up being a supervisord bug I will refile it on their bug tracker, but the problem only appears when using flask's reloading feature. 

Here's my simple flask app: 

```
from flask import Flask

app = Flask(__name__, static_url_path='')

@app.route('/start')
def start_build():
  print "Running command"
  return "Starting"

if __name__ == "__main__":
  app.run(debug=True)
```

As you'd expect, this generates the following output

```
hamiltont$ python example.py
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
Running command
127.0.0.1 - - [04/Apr/2015 18:58:13] "GET /start HTTP/1.1" 200 -
Running command
127.0.0.1 - - [04/Apr/2015 18:58:42] "GET /start HTTP/1.1" 200 -
Running command
127.0.0.1 - - [04/Apr/2015 18:58:44] "GET /start HTTP/1.1" 200 -
```

This output is generated correctly for all combinations of `python` vs `python -u` and `use_reloader=True` vs `use_reloader=False`. 

Now I try to run the application (with reloading enabled) using supervisord and this `supervisord.conf` file

```
[supervisord]
nodaemon=true

[program:flask]
command=python -u example.py

; Send stdout to console
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

; Send stderr to console
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

; Flask does not propagate signals to child processes when using debug
; mode, so this tells supervisor to send the signal to the entire 
; process group instead of just the parent
stopasgroup=true
; Send interrupt so the server is shutdown gracefully
stopsignal=INT
```

Note that I'm intentionally specifying `python -u` in my command, just to avoid issues. Here's the output: 

```
hamiltont$ supervisord -c super.conf
2015-04-04 19:02:59,762 INFO supervisord started with pid 22439
2015-04-04 19:03:00,769 INFO spawned: 'flask' with pid 22442
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
2015-04-04 19:03:01,939 INFO success: flask entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
127.0.0.1 - - [04/Apr/2015 19:04:07] "GET /start HTTP/1.1" 200 -
127.0.0.1 - - [04/Apr/2015 19:04:11] "GET /start HTTP/1.1" 200 -
127.0.0.1 - - [04/Apr/2015 19:04:11] "GET /start HTTP/1.1" 200 -
^C
2015-04-04 19:04:14,198 WARN received SIGINT indicating exit request
2015-04-04 19:04:14,198 INFO waiting for flask to die
Running command
Running command
Running command
2015-04-04 19:04:14,209 INFO stopped: flask (exit status 0)
```

So until I hit `Ctrl-C` to terminate, the stdout was being buffered. If I disable reloading, then everything works as expected: 

```
hamiltont$ supervisord -c super.conf
2015-04-04 19:06:49,711 INFO supervisord started with pid 22462
2015-04-04 19:06:50,715 INFO spawned: 'flask' with pid 22465
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2015-04-04 19:06:52,268 INFO success: flask entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Running command
127.0.0.1 - - [04/Apr/2015 19:06:54] "GET /start HTTP/1.1" 200 -
Running command
127.0.0.1 - - [04/Apr/2015 19:06:57] "GET /start HTTP/1.1" 200 -
Running command
127.0.0.1 - - [04/Apr/2015 19:06:58] "GET /start HTTP/1.1" 200 -
^C
2015-04-04 19:07:03,959 WARN received SIGINT indicating exit request
2015-04-04 19:07:03,960 INFO waiting for flask to die
2015-04-04 19:07:03,968 INFO stopped: flask (exit status 0)
```

I can also generate the expected output by manually wrapping stdout at the top of my `example.py` file

```
import sys
import os
sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', 0)
```

**Comment by ThiefMaster** [comment]
Are you trying to run the dev server in production? Because that's a **terrible idea**.

**Comment by hamiltont** [comment]
Ha, no, that's definitely not what I'm doing

**Comment by untitaker** [comment]
It's a bug in Flask's dependency Werkzeug, but to my knowledge it's also impossible to fix. My advice would be to explicitly restart the server in your deployment scripts.

I don't get why you're starting the dev server via supervisord though.

**Comment by hamiltont** [comment]
@untitaker Good to know. Can you link me to the bug report? I'd like to read it. So far my workaround is to just check if I'm running flask in debug mode and wrapper stdout, and that has been working fine. 

> I don't get why you're starting the dev server via supervisord though.

My system has 5+ components needed when turning on/off. They mostly need to be restarted together. Its unfeasible to cycle through terminals just to be able to say "restart everything". I first used some bash scripts, but that's fairly inflexible, so switched to supervisor. It enables me to actually develop quicker than a snail

**Comment by untitaker** [comment]
>Good to know. Can you link me to the bug report? I'd like to read it.

There is none, only related bugs in Werkzeug (perhaps under the "reloader" label). I'll try to summarize the main problem here:

Take a look at [this line in Werkzeug](https://github.com/mitsuhiko/werkzeug/blob/master/werkzeug/_reloader.py#L96):

     args = [sys.executable] + sys.argv

That's Werkzeug's attempt at recreating the original command that was used to start the server, As you can see, it doesn't take any options for the Python command itself into account.

**Comment by ThiefMaster** [comment]
If all you need is `-u` to be active, simply set `PYTHONUNBUFFERED=1` in your environment. That does the same as `-u`.

**Comment by hamiltont** [comment]
Great, thanks for the help!!

**Comment by mirrorcoloured** [comment]
If anyone finds this in the future, you can call
`sys.stdout.flush()`
after print to correct this behavior.
