### ISSUE TITLE
5 years, still not 1.0! what are you thinking about, pocoo?

### ISSUE THREAD

**Issue by heziqiang99** [mitsuhiko/flask#1423]
5 years, still not 1.0! what are you thinking about, pocoo?

**Comment by ThiefMaster** [comment]
Passive-aggressive comments are really not necessary. :)

Does a major version >0 really matter that much? Flask is already very stable and production-ready, even without being version 1.0.

**Comment by untitaker** [comment]
@heziqiang99 What's the point?

**Comment by hbrls** [comment]
@untitaker One of my managers refused to use a lib not even 1.0. I'm still struggling with tornado now by making the code and arch look like Flask.

**Comment by untitaker** [comment]
That's ridiculous thinking then, because half of the Python ecosystem is under 1.0.

**Comment by ThiefMaster** [comment]
Please point your manager to this issue so we can tell him that he's an idiot if he goes by version number instead of maturity. :)

**Comment by untitaker** [comment]
That might not be such a good idea but you could argue that Flask, as you said, has been out for five years, and people still do new projects with it.

**Comment by davidism** [comment]
Just tell him it's currently version 10, the string just looks like that for backwards compatibility.  But seriously: stability, maturity, and support matter a lot more than a version number.

**Comment by Kareeeeem** [comment]
Is the current dev version not stable enough to do a release? Honest question that I've asked somewhere else before but didn't really get an answer. 

Armin Ronacher also echo'd the need for a new release last year in this metaflask discussion: https://github.com/pocoo/metaflask/issues/55.

**Comment by ThiefMaster** [comment]
1.0 means no breaking api changes until 2.0. such a release is not done lightly... I'd rather see a 0.11 so there's mroe chances to make sure the api doesn't have any stinky parts in it.

**Comment by untitaker** [comment]
I'd have no problem with releasing major versions more often. I don't expect the new APIs to be 100% correct for 1.0, and I would rather release 2.0 the next month than having a shitty API for the next 5 years.

**Comment by Diaoul** [comment]
I wish I could get a taste of 1.0 through maybe pre-releases like alphas? I'd like to try the new CLI system. It would help to get a glipse of what 1.0 will look like without installing the master branch.

I don't care if it's named 1.0 or 0.11 or anything else, I just want the features tagged :sparkles:

**Comment by mreinhardt** [comment]
Just to comment for anyone who is unsure of stability or needs to convince their managers: we're using Flask on a distributed production system that runs between 1k-10k rpm depending on peaks and crawls and such. We built the current system to *replace* a tornado system that was jank. Any issues we've had thus far have been with other parts of the system, not Flask.

In my experience, there is very little risk factor to choosing Flask in its current version.

**Comment by zprima** [comment]
I think the issue here is that flask 0.10.1 was released in 2013, and after 2 years, there are no security or bug fixes or anything released. My managers where not that hard to convince, but they raised concern, why no fixes after so long time.

**Comment by untitaker** [comment]
@zprima Security releases were just not necessary in Flask itself (to my knowledge) and we've come to a point where there are mostly bugs left whose fix would break backwards compatibility.

There are many issues with the current maintenance process, but you should also consider the releases of Werkzeug and Jinja to determine if bugs get fixed.

**Comment by hbrls** [comment]
@mreinhardt I trust Flask and I use it for my own projects. However the decision makers had not time to learn how good it is.

**Comment by untitaker** [comment]
Closing because there's nothing to fix.

**Comment by alexandre** [comment]
P.S you can tell to your manager that the president Obama uses Flask:
http://arstechnica.com/information-technology/2012/11/20/how-team-obamas-tech-efficiency-left-romney-it-in-dust/

\</troll\>
