### ISSUE TITLE
Are there any interest in displaying current_user when logging exceptions?

### ISSUE THREAD

**Issue by nextcoder** [mitsuhiko/flask#1424]
I am sure I am not the only one who would like to see who was the current_user when an exception happens especially in production environments.

Currently, the "standard" way to accomplish this is to use logging.LoggingAdapter. But since every flask exception is hardwired to go to the app.logger, how can I use the adapter method?

**Comment by untitaker** [comment]
Is current_user from an extension? Flask doesn't have this object.

**Comment by pbu88** [comment]
@untitaker `current_user` is a proxy used in Flask-Login extension.

@nextcoder Recently I wrote a very simple snippet to output custom post-mortem info to the logs: http://flask.pocoo.org/snippets/127/. This should be easily modified to include the current_user in the dump. Maybe it can help you.

Nevertheless, this is not the place to ask questions like this, this is an issue tracker, not a QA forum, I think this suits better in StackOverflow.

**Comment by untitaker** [comment]
Right, please only discuss feature requests for Flask itself. If you think Flask's logger needs some facilities so that Flask-Login can add some information to the logs, this would be the right topic to open an issue about.

**Comment by nextcoder** [comment]
Alright, sorry for asking the wrong question in the wrong forum.

**Comment by untitaker** [comment]
No problem. I think this is worth reporting to [Flask-Login](http://github.com/maxcountryman/flask-login), and I'm sure it *would* require some changes in Flask or Werkzeug. But this is not the right place to *start* the conversation.
