### ISSUE TITLE
the master version of flask has not module.py, but 0.10.1 has it 

### ISSUE THREAD

**Issue by GreatmanBill** [mitsuhiko/flask#1425]
I use the flask extension flask-theme,  it has a import ：
from flask import (Module, send_from_directory, render_template, json,
                     _request_ctx_stack, abort, url_for) 
the master version has no Module
so I reinstall flask to 0.10.1, but it hasn't cli.py 

so , I want to know, the module.py is not necessary in the fulture?

**Comment by sh4nks** [comment]
Modules were deprecated a long time ago. Use Blueprints instead.

**Comment by GreatmanBill** [comment]
ok, thanks
