### ISSUE TITLE
Explicit show the content-type of response

### ISSUE THREAD

**Issue by felipevolpone** [mitsuhiko/flask#1434]
Hey guys, I was thinking that could be a good ideia create a decorator to put in the head of method, to show what kind of content-type that rest service will return. 

Something like that:
```python

@return_json
@app.route('/user/email')
def get_user_email():
   return {'email': 'example@email.com'}
```

So, in the return_json decorator we could change the content-type of response. If someone think that is a good ideia, I can implement and send a pull request.

**Comment by ThiefMaster** [comment]
That's extremely easy to implement in your own application. No need for it to be in Flask itself.

Besides that, if you return JSON using the `jsonify` function it'll already set the proper content-type header.

**Comment by untitaker** [comment]
What @ThiefMaster said + Flask isn't focused on JSON APIs, or even APIs more than it is on frontend dev, so a special decorator isn't really warranted IMO.

**Comment by felipevolpone** [comment]
Ok! Tkx for explanation.
