### ISSUE TITLE
Change first argument in a Class methoc to 'self'

### ISSUE THREAD

**Issue by andyxning** [mitsuhiko/flask#1440]
I recently run into the **app.logger** usage. However, when i read the source code in flask **v0.10.1** , i find that it uses `x` instead of `self` as the first method argument in class [**DebugLogger**](https://github.com/mitsuhiko/flask/blob/0.10.1/flask/logging.py#L26) and [**DebugHandler**](https://github.com/mitsuhiko/flask/blob/0.10.1/flask/logging.py#L32).

Can we just update this calling convention.

**Comment by grahamlyons** [comment]
Sounds perfectly reasonable. Submit a pull request?

**Comment by andyxning** [comment]
Ok, i will make it later.



++++++
Ning Xie


2015-04-19 2:06 GMT+08:00 Graham Lyons <notifications@github.com>:
