### ISSUE TITLE
small inaccuracy in get_json documentation

### ISSUE THREAD

**Issue by lumilux** [mitsuhiko/flask#1442]
In the documentation for [`get_json`](http://flask.pocoo.org/docs/0.10/api/#flask.Request.get_json), the *silent* parameter is described as "if set to _False_ this method will fail silently and return _False_". It should probably say "if set to _True_ [...]" instead.

**Comment by omarkhd** [comment]
I took a look at the rst method documentation and it is correctly defined: "if set to True this method will fail silently and return None".

**Comment by untitaker** [comment]
https://github.com/mitsuhiko/flask/commit/3e90de2e10cfde5803fab87768430cffff7c78a0

@omarkhd thanks for pointing this out!
