### ISSUE TITLE
url_for with multiple query parameters escape '&'

### ISSUE THREAD

**Issue by grubberr** [mitsuhiko/flask#1444]
```
# cat templates/t.html 
{{ url_for('url', key1='val1', key2='val2') }}
```
```
from flask import Flask, render_template
app = Flask(__name__)

@app.route('/url')
def url(): pass

with app.test_request_context():
    print render_template('t.html')
```

This script produce such output:
```
/url?key2=val2&amp;key1=val1
```

I see that query string params separator '&' escaped -> '\&amp;'
is it bug ?

**Comment by untitaker** [comment]
No. Is that behavior a problem to you?

**Comment by ThiefMaster** [comment]
http://stackoverflow.com/questions/3493405/do-i-really-need-to-encode-as-amp

tl;dr: it's best to always  escape `&` in HTML documents.

**Comment by grubberr** [comment]
hm it seems I slightly mess URL-escaping and HTML-escaping
I just thought that url_for build url (with URL-escaping all individual parameters) and NOT HTML-escape final result

**Comment by ThiefMaster** [comment]
You shouldn't have to escape anything manually when using flask+jinja except in some very rare cases (such as putting `|tojson` results outside script tags).

**Comment by grubberr** [comment]
for some reason I thought that jinja2 not autoescape result of url_for function
but yes I was wrong

I just stuck with this escaping problem when pass result of url_for to javascript http.open function
It started to work only when I turned off auto HTML-escaping:
http.open('GET', {{ url_for()|safe }}
