### ISSUE TITLE
after_request excuted twice

### ISSUE THREAD

**Issue by zhangwen9229** [mitsuhiko/flask#1459]
Use plugin：flask-restful
in app.py:(please see my annotation)    
def process_response(self, response):
        ctx = _request_ctx_stack.top
        bp = ctx.request.blueprint
        funcs = ctx._after_request_functions         # here is None
        if bp is not None and bp in self.after_request_funcs:
            funcs = chain(funcs, reversed(self.after_request_funcs[bp]))
        if None in self.after_request_funcs: 
            funcs = chain(funcs, reversed(self.after_request_funcs[None]))     # here is <itertools.chain object at 0x000000000449FFD0>
        for handler in funcs:               #  then this loop be excuted twice
            response = handler(response)
        if not self.session_interface.is_null_session(ctx.session):
            self.save_session(ctx.session, response)
        return response

please help..

**Comment by ThiefMaster** [comment]
> please help..

Please format your code properly. Click on *Markdown supported* on top of the editor to read the formatting help from GitHub.

Also, if the problem only occurs in Flask-Restful, it should go to the issue tracker of that extension.

**Comment by zhangwen9229** [comment]
All in all,thank you for your reply.
