### ISSUE TITLE
Flask Documentation PDF is missing

### ISSUE THREAD

**Issue by smorin** [mitsuhiko/flask#1460]
Flask Documentation PDF is missing

Read the documentation or download as PDF and zipped HTML
Links to http://flask.pocoo.org/docs/flask-docs.pdf and http://flask.pocoo.org/docs/flask-docs.zip

Both of which are missing.

**Comment by davidism** [comment]
Duplicate of pocoo/metaflask#7 and [all these](https://github.com/mitsuhiko/flask/issues?q=pdf).

**Comment by kierdwyn** [comment]
Try this link:
https://media.readthedocs.org/pdf/flask/latest/flask.pdf

**Comment by soerendip** [comment]
The link is dead.
