### ISSUE TITLE
uWSGI / nginx documentation is incorrect

### ISSUE THREAD

**Issue by jribbens** [mitsuhiko/flask#1464]
The Flask documentation for how to use it with uWSGI and nginx is incorrect. As the uWSGI docs say at http://uwsgi-docs.readthedocs.org/en/latest/Nginx.html#hosting-multiple-apps-in-the-same-process-aka-managing-script-name-and-path-info, "ancient uWSGI versions used to support the so called “uwsgi_modifier1 30” approach. Do not do it. it is a really ugly hack". The documentation should be updated to talk about the `manage-script-name` and `mount` options instead.

**Comment by jeffwidman** [comment]
@davidism just in case you didn't see my comment on the PR... I dug into this pretty heavily a few weeks ago--submitted a couple of fixes to the uWSGI docs. The updates in #1558 are solid. Like Flask, uWSGI offers more than one way to do things, so there are alternative configs, but this works and is a lot better than what the Flask docs currently recommend. I don't see any reason to hold off on merging it.

**Comment by mitsuhiko** [comment]
@jeffwidman just to carify: do you suggest merging #1558?

**Comment by jeffwidman** [comment]
Yes

**Comment by mitsuhiko** [comment]
Merged :)

**Comment by jeffwidman** [comment]
:+1:
