### ISSUE TITLE
packaging docs outdated

### ISSUE THREAD

**Issue by wimglenn** [mitsuhiko/flask#1465]
from here ->  http://flask.pocoo.org/docs/0.10/patterns/distribute/

distribute has gone the way of the norwegian blue, hence dead link at  http://python-distribute.org/distribute_setup.py  should be cleaned up

**Comment by keyan** [comment]
Thanks @wimglenn.

To any new contributors that are interested in fixing this, the relevant file is:
https://github.com/mitsuhiko/flask/blob/master/docs/patterns/distribute.rst

It may make sense to completely remove this section and adjust any links to it. It seems mostly outdated.

**Comment by thatarchguy** [comment]
Distribute is deprecated.
I don't think this warrants deleting the page, since the information is still relevant. 
Should the page be renamed to setuptools and updated accordingly?

**Comment by keyan** [comment]
@thatarchguy, I disagree. The old docs will exist if anyone would like to look at them later, this page has information that should not be used. Renaming/updating is akin to making a new page for setuptools, the two tasks can probably be done in separate PRs.

**Comment by RonnyPfannschmidt** [comment]
the information is mostly the same, rename and word replace seems to be the least effect to go from bad back to good

**Comment by Tillychang** [comment]
i just learn python for few days,can i try it?

**Comment by davidism** [comment]
move discussion to pull request #1588

**Comment by cgoldberg** [comment]
just submitted PR #1795 to finish fixing this (#1588 left some references to Distribute)
