### ISSUE TITLE
mod_wsgi (Apache) Troubleshooting tips needs one more

### ISSUE THREAD

**Issue by dansalmo** [mitsuhiko/flask#1469]
In http://flask.pocoo.org/docs/0.10/deploying/mod_wsgi/
I ran into an issue when following the guide to configure a current working Flask app for Apache.  It would have been much easier to discover the cause if the following tip was given:

Problem: application runs but can not access other files:

For WSGI applications, all paths used should always be absolute path names.  Even though the app will work fine using relative paths with the simpler python serving method, they will not work with WSGI.

**Comment by davidism** [comment]
I'm not sure what paths you're referring to, but as far as I know everything is relative to the app root in Flask, so this isn't actually true.
