### ISSUE TITLE
route function quit unexpectedly

### ISSUE THREAD

**Issue by shuokay** [mitsuhiko/flask#1470]
When I call a python wrapper of C++ code in a flask route function, the flask route function quit unexpectedly. But if I call the wrapper from a normal python script ,everything goes well. Is there any condition that flask route function quit automatically?

**Comment by ThiefMaster** [comment]
Define "quit unexpectedly".

But it sounds a lot like your native function is broken. Unlike Python code, bugs in C or C++ code can easily result in undefined behavior and sometimes crash while working in a slighly different environment.

**Comment by untitaker** [comment]
What @ThiefMaster said, and please provide a good testcase before saying this is a problem with Flask.
