### ISSUE TITLE
Adding after_server_run

### ISSUE THREAD

**Issue by srirams6** [mitsuhiko/flask#1471]
It would be nice to have a feature that would let a function be called after the server is started. As far as I've seen there is no such feature.

**Comment by ThiefMaster** [comment]
Hmm I don't really see the use case for this, especially considering that 
the built-in server is only for development..

**Comment by srirams6** [comment]
A use case would be as follows.

Let us say that I want to open a browser window as soon as my server starts. If I call the open function before the server run, there is a race condition. If I call after, the server run will block.

I agree that this is an isolated use case, but it would be a nice function to have imo :)

**Comment by ThiefMaster** [comment]
Ok, that makes some sense. However, depending on how it works it'd interfere with the reloader (opening the browser whenever the reloader restarts the server etc).

IMO it'd be overkill to add it to the Flask core.

**Comment by srirams6** [comment]
Fair enough. That's what I'm doing at the moment.

**Comment by untitaker** [comment]
I certainly don't want to add this in form of a hook that is available in production, as we can't make any guarantees that the hook is run in e.g. a CGI environment.

The only way I could see this work without any problems is a wrapper script that spawns the server and the browser tab. https://github.com/mitsuhiko/flask/issues/1179 and the PR for Werkzeug can be useful for this without hitting the local port with requests until the request is answered.

In addition to all those technical problems I agree with @ThiefMaster that this is out of scope for Flask anyway.
