### ISSUE TITLE
Flask server stops responding to new HTTP connections

### ISSUE THREAD

**Issue by mk270** [mitsuhiko/flask#1473]
After a day or two, my Flask app stops noticing new connections; strace says:

mk@pling /proc/31539/fd> strace -p 31539 -e '!stat'
Process 31539 attached - interrupt to quit
select(0, NULL, NULL, NULL, {0, 805175}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)
select(0, NULL, NULL, NULL, {1, 0}^C <unfinished ...>
Process 31539 detached

(note that the stat() calls between each select() have been omitted).

So select() is being called without any fds, basically as a blocking primitive, but I seem to have the following fds:

lsof -p etc:
python  31539   mk    3u  IPv4 141934535      0t0      TCP *:5000 (LISTEN)
python  31539   mk    4u  IPv4 142787301      0t0      TCP 93.93.128.61:5000->61.240.144.65:60000 (ESTABLISHED)

So it should by rights be select()ing on fd 3 at the very least.

**Comment by mk270** [comment]
Ah, tiresomely, I forgot -f to strace - so the above output is misleading

**Comment by untitaker** [comment]
Are you using the development server in production? `app.run` can only serve one connection at a time, it's very easy to freeze the server by leaving one connection open.

**Comment by mk270** [comment]
And I have to use some external nonsense like gunicorn to work around this?

**Comment by untitaker** [comment]
Yes.

Flask is a web framework, not a server. Not including a scalable server sacrifices a bit of usability for flexibility. I don't know your background, but that distinction is not unique to Flask.

**Comment by mk270** [comment]
thanks
