### ISSUE TITLE
Add flask laptop decals sale link to the website

### ISSUE THREAD

**Issue by mnickey** [mitsuhiko/flask#1474]
This is neither a bug or issue but a request.
Where can I find laptop decals for flask? I'm loving this framework and would like to promote it with a laptop decal or sticker but I cannot find any.   

Can we make this happen? Stickermule was suggested on reddit but I think this should be held in flask 'store' should this come about.

**Comment by untitaker** [comment]
The Flask store is powered by Spreadshirt, who seem to sell pretty much anything but stickers... given that, I think Stickermule would be a good idea.

FWIW I don't think anything of this has to be official merchandise, a third-party might sell it as well.

**Comment by nickjj** [comment]
I spoke with Armin about this the other day. They are up for sale on Stickermule:

https://www.stickermule.com/marketplace/6037-flask-web-framework

**Comment by untitaker** [comment]
Nice! We should put those on the website.

**Comment by davidism** [comment]
Cool, I'll take some with me to PyCon this year.  Added in mitsuhiko/flask-website@f344f0857fa0bcc7d8c63d0c186f82abd0e83712, although I'm not sure when that will go live.
