### ISSUE TITLE
Remove Blueprint.view_functions

### ISSUE THREAD

**Issue by phryk** [mitsuhiko/flask#1477]
https://github.com/mitsuhiko/flask/blob/master/flask/blueprints.py#L104

Blueprint.view_functions should be removed as it does nothing besides potentially confuse people.

**Comment by jmagnusson** [comment]
Does it really do nothing? It seems to be used [here](https://github.com/mitsuhiko/flask/blob/master/flask/blueprints.py#L185).

**Comment by phryk** [comment]
Yes, it really does nothing, that is state.app.view_functions. Made the same mistake first :P

**Comment by davidism** [comment]
@jmagnusson no, that's `app.view_functions`.  It looks like `Blueprint.view_functions` isn't even populated.

**Comment by phryk** [comment]
Exactly, it always just is {}. I wanted to use it, that's how I noticed.
Already talked in freenode/#pocoo about this before posting.

I also removed that line locally without any averse effects, I don't know how to run the developer tests though.

**Comment by jmagnusson** [comment]
Okay thanks. Just wanted clarification.
