### ISSUE TITLE
Flask keep-alive

### ISSUE THREAD

**Issue by kvarga** [mitsuhiko/flask#1478]
Is there a way to send intermittent responses to client to avoid timeout for long-running tasks (~2minutes)?

If not, I guess I will have to do the following flow:

1. User requests a webpage
2. Check if that webpage is available in cache
3. If not, redirect them to a holding page that checks ~15 seconds if that request is ready
4. Load the response

Seems less than ideal, but gets the added benefit of showing some sort of progress indicator to the user

**Comment by davidism** [comment]
Use [Celery](http://www.celeryproject.org/) or another task queue to run the long tasks in the backround, rather than running them in one of the web app threads.

**Comment by untitaker** [comment]
You want response streaming (or polling via javascript) in combination with a task queue such as celery or rq.

Please don't use the bugtracker for support requests.
