### ISSUE TITLE
Any new release ?

### ISSUE THREAD

**Issue by nlamirault** [mitsuhiko/flask#1492]
Is a new version planned?
Last version 0.10.1 is very old : on Jun 14, 2013

**Comment by ThiefMaster** [comment]
Yes, obviously

**Comment by tschundeee** [comment]
Get it out the door. So much has happened on the repo since 2013. Why not create a 1.0.0-beta1 and let people try it out.

**Comment by untitaker** [comment]
Because nothing is finished at all. Take a look at the milestones.

**Comment by untitaker** [comment]
We could make a few alphas though, good point.

**Comment by bastianh** [comment]
alphas would be great ;)

**Comment by tschundeee** [comment]
Maybe the milstones need to be readjusted in order to get a new release out ;)

**Comment by mileswd** [comment]
+1 for alpha builds
