### ISSUE TITLE
Tutorial    Step 5: The View Functions

### ISSUE THREAD

**Issue by xiekakaban** [mitsuhiko/flask#1500]
The following code is in the tutorial:

~~~python
@app.route('/add', methods=['POST'])
def add_entry():
    if not session.get('logged_in'):
        abort(401)
    g.db.execute('insert into entries (title, text) values (?, ?)',
                 [request.form['title'], request.form['text']])
    g.db.commit()
    flash('New entry was successfully posted')
    return redirect(url_for('show_entries'))
~~~

The second arg to `execute` should be a tuple, not a list.  `g.db.execute('INSERT INTO entries(title,text) VALUES(?,?)',(request.form["title"],request.form["text"]))`

**Comment by untitaker** [comment]
I suppose either is fine.

**Comment by ThiefMaster** [comment]
btw, you can fence code blocks in triple backticks to format them as code. see https://guides.github.com/features/mastering-markdown/

**Comment by davidism** [comment]
There's nothing wrong with using a list here.  Using a tuple, while possibly "nicer" in this situation, doesn't change its behavior.  New developers tend to misplace the parentheses, especially when it's a 1-tuple, which is easier to spot with list brackets.
