### ISSUE TITLE
How to detect ssl(schema) protocol correctly with request.url_root?

### ISSUE THREAD

**Issue by emamirazavi** [mitsuhiko/flask#1503]
I'm using nginx + gunicorn + flask. With request.url_root  i can not detect schema correctly because it's always http! although i'm routing with https configured in nginx!
e.g i browse this url:
```
https://www.example.com/hello
```
and request.url reads:
```
http://www.example.com/hello
```

**Comment by ThiefMaster** [comment]
is nginx->gunicorn a http connection by any chance? in that case flask doesn't even know that the user was using https...

**Comment by untitaker** [comment]
This is not a Flask issue. You're supposed to use [ProxyFix](http://werkzeug.pocoo.org/docs/0.10/contrib/fixers/#werkzeug.contrib.fixers.ProxyFix) and make nginx set the appropriate `X-Forwarded` headers.
