### ISSUE TITLE
Question:  reload process too slow

### ISSUE THREAD

**Issue by Chaniel** [mitsuhiko/flask#1504]
everytime when I changed some file , the flask will autoreload, but the reload process is too slow!
how solve this ?

![reload](https://cloud.githubusercontent.com/assets/3492992/8229198/4d64d922-15e7-11e5-836d-f813e94fdf1a.png)

**Comment by untitaker** [comment]
Which version of Flask and Werkzeug are you running? Have you tried with the `watchdog` reloader by doing `pip install watchdog`?

**Comment by davidism** [comment]
Werkzeug includes a default reloader that doesn't require external dependencies but isn't very efficient.  Install [watchdog][1] with `pip install watchdog` and that will be used instead.

[1]: https://pythonhosted.org/watchdog/
