### ISSUE TITLE
JSON Encoding in Python 3

### ISSUE THREAD

**Issue by carsongee** [mitsuhiko/flask#1505]
I'm trying to port an application to python 3 and ran into this encoding issue with this unit test:
```python
        with app.test_request_context():
            from flask import jsonify
            test_data = {'test': 1}
            response = jsonify(test_data)
            self.assertEqual(
                response.response,
                [json.dumps({'test': 1}, indent=2)]
            )
```
and getting this:
```
E           AssertionError: Lists differ: [b'{\n  "test": 1\n}'] != ['{\n  "test": 1\n}']
E
E           First differing element 0:
E           b'{\n  "test": 1\n}'
E           {
E             "test": 1
E           }
E
E           - [b'{\n  "test": 1\n}']
E           ?  -
E
E           + ['{\n  "test": 1\n}']
```
so it appears that somewhere along the line the returned json isn't getting decoded to UTF-8 and results in having the `b` designator in the output.  Is this maybe just something I'm doing wrong? The test passes in Python 2.7.

I'm using these versions and Python 3.4.2 and 3.3.6:
```
Flask==0.10.1
Flask-Assets==0.10
Jinja2==2.7.3
MarkupSafe==0.23
Werkzeug==0.10.4
itsdangerous==0.24
```

**Comment by untitaker** [comment]
Your unit test is wrong.

- `response.response` is not guaranteed to be a string, it merely happens to be.
- If a string, `response.response` is (apparently) always a bytestring, which means `"foo"` on Python 2 and `b"foo"` on Python 3.

You probably want to use `response.get_data(as_text=True)`.

**Comment by carsongee** [comment]
Thanks for the fast response, that did the trick.
