### ISSUE TITLE
flash(...) won't work!

### ISSUE THREAD

**Issue by Tekkkz** [mitsuhiko/flask#1506]
Hello!
The flash(...) function doesn't work at me – it raises an internal server error!

My code:
@app.route('/')
def main():
    flash('This message will be visible!')
    return str(get_flashed_messages())

that's all! And with just return "xxx" it works.

What's the problem? I'm using python 2.6.

**Comment by untitaker** [comment]
Please enable `debug` mode (`app.debug = True`) and retrieve the actual error message.

**Comment by Tekkkz** [comment]
How to activate the debug?

**Comment by untitaker** [comment]
Please read the quickstart, it is all explained there: http://flask.pocoo.org/docs/0.10/quickstart/#debug-mode

**Comment by Tekkkz** [comment]
I activated the debug, here you can check it out: http://hubb.tekkkz.com/
So why wont flash() work?

**Comment by ThiefMaster** [comment]
NEVER expose the debugger with default settings!

http://hubb.tekkkz.com/console

That was a python shell where everyone could run code on your machine. I've killed it (`os.kill(os.getpid(), 9)`) before someone does worse stuff.

**Comment by Tekkkz** [comment]
I did this now:
SECRET_KEY = 'ae58c6914d'
app = Flask(__name__)
app.config.from_object(__name__)

But it still doesn't work??

**Comment by untitaker** [comment]
@Tekkkz Read what's on the page I linked. The debugger shows you the concrete error message where normally a 500-error would stand.

Also listen to @ThiefMaster who already told you that publishing an app with `debug=True` like that is a security nightmare. So please **shut the server down** and run it locally.

**Comment by untitaker** [comment]
Also you should've used an official support channel, like the `#pocoo` IRC channel on Freenode. The bugtracker is not an appropriate one.

**Comment by Tekkkz** [comment]
it works now, thx

**Comment by untitaker** [comment]
Please disable the debug mode, your server is vulnerable...
