### ISSUE TITLE
where is SESSION_REFRESH_EACH_REQUEST?

### ISSUE THREAD

**Issue by EricQAQ** [mitsuhiko/flask#1508]
In flask-0.10.1, I can't find `SESSION_REFRESH_EACH_REQUEST` in `default_config`. But `SESSION_REFRESH_EACH_REQUEST` is in the doc. 
That means, in flask-0.10.1, there are 23 elements in `default_config`, but 24 in the doc of the flask.

**Comment by ThiefMaster** [comment]
It does not exist in 0.10.1 at all. It was added later and is currently only in master: d1d835c02302884b2db1cab099b3ea6a84f41d32
