### ISSUE TITLE
Does the 'docs/quickstart.rst:A Minimal Application' missed something?

### ISSUE THREAD

**Issue by eailfly** [mitsuhiko/flask#1513]
I think the first application should be (and the official site is):
```python
from flask import Flask
app = Flask(__name__)

@app.route('/')
def hello_world():
    return 'Hello World!'

if __name__ == '__main__':
    app.run()
```
In this doc it's missing:
```python
if __name__ == '__main__':
    app.run()
```

**Comment by zvyn** [comment]
The documentation works as described, if you have the newest version of flask and use Python 3.
Starting the app with `flask -a name run` seems to be the recommended way of using it now.
