### ISSUE TITLE
cross domain

### ISSUE THREAD

**Issue by lisper-inmove** [mitsuhiko/flask#1516]
i met cross-domain and i use this decorate to solve this problem,
    http://flask.pocoo.org/snippets/56/
but only if
@crossdomain(origin='*') 
can success,and when i try to point a specific domain such as @crossdomain(origin="test.123.com") or 
@crossdomain(origin=["test.123.com"]), it failed. what should i do to point a specific domain?
i need help, thx.

**Comment by lisper-inmove** [comment]
question for cross domain.

**Comment by giwa** [comment]
I did not test this but how about put `http://test.123.com` ?
Hopefully, this would help.

**Comment by lisper-inmove** [comment]
i have tried this, failed.- -!

**Comment by keyan** [comment]
Is this a bug? Try asking in IRC channel or stackoverflow for help.

**Comment by gkrasulya** [comment]
Can you show `Access-Control-Allow-Origin` header when you request your endpoint?
