### ISSUE TITLE
sourcecode from "AJAX with jQuery" not working?

### ISSUE THREAD

**Issue by BeryllN** [mitsuhiko/flask#1517]
Hi,

I just downloaded the sourcecode for the AJAX with jQuery example (http://flask.pocoo.org/docs/0.10/patterns/jquery/). 

When i try and run index.html, it gives me an error: "Uncaught ReferenceError: $ is not defined" for index.html:5.
For layout.html, it gives 2 errors:
"GET http://localhost/templates/script.js" for layout.html:5
"Uncaught SyntaxError: Unexpected token {" for layout.html:7

Consequently, the example doesn't work as no result is generated if you put 2 numbers in the input boxes.

Cheers

**Comment by BeryllN** [comment]
The previous error comes from loading index.html. 
Two more are generated while loading layout.html:
"GET http://localhost/templates/script.js" for layout.html:5
"Uncaught SyntaxError: Unexpected token {" for layout.html:7

**Comment by Aayush-Kasurde** [comment]
I am able to run "AJAX with jQuery" example without any error. Could you please add more details about your source code and development environment?

**Comment by BeryllN** [comment]
Sorry, I kind of forgot about that and I won't be able to help with that anymore since I changed lots of settings here and there and it's working now, but I wouldn't be able to tell you what made it working :/
