### ISSUE TITLE
Any plans for new versions? Maybe 1.0?

### ISSUE THREAD

**Issue by surrealcristian** [mitsuhiko/flask#1518]
Hello everybody.

Please, forgive my poor english, and do not get me wrong, my question is not malicious.

Actually, are any plans to reach version 1.0? Or at least reach a new version?

1.0, or a more fluid release versions can be a way to attract more users and developers.

Greetings, and thanks for the work you do in Flask.

**Comment by davidism** [comment]
Duplicate of #1492
