### ISSUE TITLE
TypeError: unbound method __init__() must be called with AssertionError instance as first argument (got FormDataRoutingRedirect instance instead)

### ISSUE THREAD

**Issue by charlax** [mitsuhiko/flask#1526]
I'm testing the behavior of a POST endpoint that issues a redirect.

I get the following traceback:

```
env/local/lib/python2.7/site-packages/flask/app.py:1820: in wsgi_app
    response = self.make_response(self.handle_exception(e))
env/local/lib/python2.7/site-packages/flask/app.py:1403: in handle_exception
    reraise(exc_type, exc_value, tb)
env/local/lib/python2.7/site-packages/flask/app.py:1817: in wsgi_app
    response = self.full_dispatch_request()
env/local/lib/python2.7/site-packages/flask/app.py:1477: in full_dispatch_request
    rv = self.handle_user_exception(e)
env/local/lib/python2.7/site-packages/flask/app.py:1381: in handle_user_exception
    reraise(exc_type, exc_value, tb)
env/local/lib/python2.7/site-packages/flask/app.py:1475: in full_dispatch_request
    rv = self.dispatch_request()
env/local/lib/python2.7/site-packages/flask/app.py:1453: in dispatch_request
    self.raise_routing_exception(req)
env/local/lib/python2.7/site-packages/flask/app.py:1439: in raise_routing_exception
    raise FormDataRoutingRedirect(request)
env/local/lib/python2.7/site-packages/flask/debughelpers.py:68: in __init__
    AssertionError.__init__(self, ''.join(buf).encode('utf-8'))
E   TypeError: unbound method __init__() must be called with AssertionError instance as first argument (got FormDataRoutingRedirect instance instead)
```

I understand the context around why we need to raise FormDataRoutingRedirect - and don't mind asserting that it's raised in my test. The problem here is the `TypeError: unbound method __init__() must be called with AssertionError`.

I'll see if I can fix it a bit later but wanted to report it first. I checked the other reported issues.

I'm using Python 2.7.9 and Flask 0.10.1

**Comment by charlax** [comment]
I first thought it happened when I was issuing a redirect using `redirect`, but it actually happens when the redirect happens inside Flask's routing engine, e.g. when trying to `POST /toasters` (no trailing slash) instead of `POST /toasters/` (trailing slash).

**Comment by untitaker** [comment]
I can't reproduce this with Python 2.7.10, in the sense that I've tried this code:

    class Foo(AssertionError):
        def __init__(self):
            AssertionError.__init__(self, 'foo')

    Foo()

**Comment by untitaker** [comment]
@charlax any updates on this?

**Comment by charlax** [comment]
Haven't been able to reproduce it lately. I think we can close.
