### ISSUE TITLE
Update docs at http://flask.pocoo.org/docs/0.10/patterns/fileuploads/

### ISSUE THREAD

**Issue by d3QUone** [mitsuhiko/flask#1527]
There is a misprint at http://flask.pocoo.org/docs/0.10/patterns/fileuploads/

`from werkzeug import secure_filename`

which is fixed in this [this repo](https://github.com/mitsuhiko/flask/blob/master/docs/patterns/fileuploads.rst)

`from werkzeug.utils import secure_filename`

**Comment by untitaker** [comment]
The new docs will be automatically built if a new version is uploaded. Check out the "development version" in the sidebar to see the docs as represented in master.
