### ISSUE TITLE
gevent has been updated to use libev instead of livevent, docs needs to be updated

### ISSUE THREAD

**Issue by WayneYe** [mitsuhiko/flask#1531]
Since gevent 1.0, it has switched from libevent to libev, please refer: http://www.gevent.org/ and http://blog.gevent.org/2010/02/27/why-gevent/.

I would like to submit a pull request for this doc page: http://flask.pocoo.org/docs/0.10/deploying/wsgi-standalone/, please confirm this update and I will prepare the pull request, thanks!

**Comment by untitaker** [comment]
please do a PR, but the stable online docs will only be updated for a release. You will be able to see the changes if you select "dev" from the sidebar though.

On 14 July 2015 20:55:05 CEST, Wayne Ye <notifications@github.com> wrote:
>Since gevent 1.0, it has switched from libevent to libev, please refer:
>http://www.gevent.org/ and
>http://blog.gevent.org/2010/02/27/why-gevent/.
>
>I would like to submit a pull request for this doc page:
>http://flask.pocoo.org/docs/0.10/deploying/wsgi-standalone/, please
>confirm this update and I will prepare the pull request, thanks!
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mitsuhiko/flask/issues/1531

-- 
Sent from my phone. Please excuse my brevity.

**Comment by WayneYe** [comment]
Thanks @untitaker for the quick reply, I will submit a PR by the end of today.
