### ISSUE TITLE
Jinja2 template not found on Large app how to wiki

### ISSUE THREAD

**Issue by kimyu92** [mitsuhiko/flask#1540]
I am using flask-wtf v0.12
Regarding to this guide: https://github.com/mitsuhiko/flask/wiki/Large-app-how-to

![screen shot 2015-07-26 at 2 28 21 pm](https://cloud.githubusercontent.com/assets/2663509/8895502/ded8471c-33a2-11e5-8d94-50aef9a33875.png)

Does anyone know is the guide obsolete or am i missing something on the setup?

**Comment by untitaker** [comment]
>This document is unofficial! It includes advice taken from many unofficial resources and never went through some sort of review process. The practices described here may be useful, but at the same time they might be dangerous too. Please keep that in mind, and do NOT add any additional information to this document. Instead, use your own site or blog. This page is kept just because many StackOverflow answers still refer to it.
