### ISSUE TITLE
Start recommending Python 3

### ISSUE THREAD

**Issue by knitori** [mitsuhiko/flask#1543]
In the docs the section [The Status of Python 3](https://github.com/mitsuhiko/flask/blob/master/docs/advanced_foreword.rst) states that you *strongly recommend using Python 2.6 and 2.7*.

Well, isn't it about time to officially recommend to use Python 3 instead? Has this been discussed before (recently)?

I myself at least never ran in any problems using Python 3 with Flask. Though, admittedly, I don't have any large projects or unusual dependencies - or maybe I just instinctively avoid anything that's not Python 3 compatible and thus never noticed problems.

Still, it seems to me that a recommendation to Python 3 is reasonable, unless you have special dependencies, and it doesn't look to me that there are many (active) Flask-* packages that require Python 2.

**Comment by methane** [comment]
>  strongly recommend using Python 2.6 and 2.7.

FYI, Python 2.6 recommendation has been dropped already.
https://github.com/mitsuhiko/flask/commit/add59a91cf45b567397db134d3e4ed4ce3ecd6da

**Comment by knitori** [comment]
I must have missed that in the link I posted. I copied the text from the current online docs. That's at least *something*...

**Comment by keyan** [comment]
@methane the online docs do not reflect the current docs in the repo. Thanks for brining this up.
