### ISSUE TITLE
Broken links on website

### ISSUE THREAD

**Issue by tigrafrog** [mitsuhiko/flask#1546]
Hi, 
looks like you have some issues with website:
Documentation:
- http://flask.pocoo.org/docs/flask-docs.pdf returns 404
- http://flask.pocoo.org/docs/flask-docs.zip returns 404
- feedback.flask.pocoo.org "Server not found"

An main question (why I try to use "feedback"):
- Any plans to full Python 3 support?

**Comment by davidism** [comment]
Duplicate of pocoo/metaflask#7 and [all these](https://github.com/mitsuhiko/flask/issues?q=pdf).
