### ISSUE TITLE
Quickstart > File Uploads > incorrect import: secure_filename

### ISSUE THREAD

**Issue by luciferz2012** [mitsuhiko/flask#1547]
It should be imported as:

> from werkzeug.utils import secure_filename

Not:

> from werkzeug import secure_filename

see http://werkzeug.pocoo.org/docs/0.10/utils/

**Comment by keyan** [comment]
Hi @luciferz2012, thanks for filing a report. It is unclear what you are trying to point out. Is there an issue with the werkzeug documentation? I couldn't find the use of `from werkzeug import secure_filename` in the link you provided. Either way this is probably a werkzeug issue and not a flask one.

**Comment by luciferz2012** [comment]
@keyan 

Sorry for the unclear expression.

I mean in the file uploads section in the quick start page http://flask.pocoo.org/docs/0.10/quickstart/#quickstart , `secure_filename` is incorrectly imported.

**Comment by keyan** [comment]
Ah, my bad! Looks like this was fixed by 17d7353d39100b5eca00f769e2564ca95457d053. Thanks for clarifying though.

**Comment by robinclark007** [comment]
@keyan thanks for the reply, I find , the flask file upload document is rather old now..
