### ISSUE TITLE
Backslash doesn't work with string URL Converter

### ISSUE THREAD

**Issue by kobybecker** [mitsuhiko/flask#1551]
I have this route

```
@app.@app.route(/resource/<string:myresource>/details')
def handler(myresource):
  ....
  ...
```

When I have a leading backslash in the name, it doesn't seem to be getting routed correctly.

This works:
```
 /resource/testresource/details/
```

This does not work:
```
 /resource/%5Ctestresource/details
```
Is this expected? What am I doing wrong?

**Comment by adeogun** [comment]
Hi @kobybecker , I just tested it out and the routing worked for me.
Try this:
@app.@app.route('/resource/<string:myresource>/details')

use <string:myresource> instead of just string:myresource

Did it fix it?

**Comment by ThiefMaster** [comment]
both of you, please format code as code in your commits (backticks around inline code, 4-space indent or triple-backtick lines around blocks). then you don't need to omit `<` etc....

**Comment by adeogun** [comment]
@ThiefMaster  thanks for the advice.
Yeah as I was saying above, use the greater than and equal than around your string:myresource as shown below and it should work.
<code class="markdown">
@app.@app.route('/resource/&lt;string:myresource&gt;/details')

&lt;string:myresource&gt; instead of just string:myresource
</code>

**Comment by kobybecker** [comment]
@adeogun hmm, so it does work on my local box. But I was trying the same on [Microsoft Azure Flask Application](https://azure.microsoft.com/en-us/documentation/articles/web-sites-python-create-deploy-flask-app/), and it doesn't work. My guess is that they're messing up the routing somehow..

**Comment by kobybecker** [comment]
I'm closing this issue, since there seems nothing wrong with Flask. Thanks!
