### ISSUE TITLE
Flask Truck Factor

### ISSUE THREAD

**Issue by gavelino** [mitsuhiko/flask#1552]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Flask** and obtained a value of **1**.

The developer responsible for this TF is:

Armin Ronacher - author of 90% of the files 

To validate our results, we would like to ask **Flask** developers the following three brief questions:

(a) Do you agree that the listed developer is the main developer of **Flask**?

(b) Do you agree that **Flask** will be in trouble if the listed developer leave the project (e.g., if he wins in the lottery, to be less morbid)?

(c) Does **Flask** have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by keyan** [comment]
Hi @gavelino, thanks for looking into this. Unfortunately this isn't the right place for this kind of forum. I'd suggest creating a google form survey and posting in the IRC channel `#pocoo`. But to answer one of you questions, I'd say @untitaker is the main contributor right now for sure. Although Armin makes big decisions, he is very busy with other projects.
