### ISSUE TITLE
Errors if server runs from in virtualenv.

### ISSUE THREAD

**Issue by F483** [mitsuhiko/flask#1553]
Start with server not install in virtualenv (works fine).

    # setup env                                                                 
    cd /tmp                                                                     
    rm -rf dataserv                                                             
    git clone https://github.com/Storj/dataserv                                 
    cd dataserv                                                                 
    virtualenv -p /usr/bin/python3 env                                          
    env/bin/python setup.py develop                                             
                                                                                
    # start server (XXX have to kill process manually)                          
    ./env/bin/python -m dataserv.app &                                          
    sleep 5                                                                     
                                                                                
    # test calls                                                                
    curl http://127.0.0.1:5000/api/register/1EdCc5bxUAsdsvuJN48gK8UteezYNC2ffU  
    curl http://127.0.0.1:5000/api/height/1EdCc5bxUAsdsvuJN48gK8UteezYNC2ffU/2  

Start with server install in virtualenv (raises 404s for some calls).

    # setup env                                                                 
    cd /tmp                                                                     
    rm -rf dataservenv                                                          
    virtualenv -p /usr/bin/python3 dataservenv                                  
    ./dataservenv/bin/pip install dataserv                                      
                                                                                
    # start server (XXX have to kill process manually)                          
    ./dataservenv/bin/python -m dataserv.app &                                  
    sleep 5 # wait for server to start                                          
                                                                                
    # test calls                                                                
    curl http://127.0.0.1:5000/api/register/1EdCc5bxUAsdsvuJN48gK8UteezYNC2ffU  
    curl http://127.0.0.1:5000/api/height/1EdCc5bxUAsdsvuJN48gK8UteezYNC2ffU/2

**Comment by samwwwblack** [comment]
This isn't a bug in Flask, as the `set_height` endpoint doesn't exist in version 1.0.1 of `dataserv` and didn't appear until 10 days ago.
A new version needs releasing and pypi updating.

**Comment by F483** [comment]
I cant believe I didn't notice that, thanks samwwwblack!
