### ISSUE TITLE
Flask g persisting across requests in test suite

### ISSUE THREAD

**Issue by cmanallen** [mitsuhiko/flask#1563]
`g` seems to be persisting longer than it should.  My understanding is that `g` only exists during a request's context.  It shouldn't be persisted across multiple separate requests.

**My auth handling**
When you visit the resource a token is used to determine who you are.  Once we get the user_id from that token we persist it like the below code.

```python
if '_auth' not in g:
    g._auth = Auth(user_id=user)
return g._auth
```

**Test Setup**
```python
def test(self):
    get = self.client.get('users', headers=make_headers())
    raise Exception(g._auth.user_id) # returns the user id outside the request context
```

Any ideas as to why `g` would be available?  Let me know if you need more information.  I wasn't sure how much to include.

**Comment by ThiefMaster** [comment]
It's stored on the app context. During a normal request both contexts have roughly the same lifetime.

**Comment by cmanallen** [comment]
@ThiefMaster Ah, so `g` will persist for the lifetime of that individual test?

**Comment by ThiefMaster** [comment]
Depends on when you push/pop the app context

**Comment by cmanallen** [comment]
In my case, it isn't popped until cleanup.  I'll look into that.  Thanks for the help dude!
