### ISSUE TITLE
support unicode filename at download attachement by send_file in helper lib

### ISSUE THREAD

**Issue by AndCycle** [mitsuhiko/flask#1570]
current send_file implement a traditional method to assign download filename,
according to RFC 5987 there is a method to have utf-8 encoding in it which is support by all modern browser nowadays,

I use this line to make it

    rv.headers['Content-Disposition'] = "attachment; filename*=UTF-8''%s"%(urllib.quote_plus(filename.encode('utf-8')))

I am not using headers.add,
because you can see there have to use asterisk character which is nasty

ref:
* http://stackoverflow.com/questions/93551/how-to-encode-the-filename-parameter-of-content-disposition-header-in-http
* http://tools.ietf.org/html/rfc5987

**Comment by davidism** [comment]
duplicate of #1286

**Comment by AndCycle** [comment]
duplicate
