### ISSUE TITLE
@app.after_request should be able to process a non-response into a response

### ISSUE THREAD

**Issue by SirCmpwn** [mitsuhiko/flask#1571]
That is, the route should be able to return anything and after_request should be able to take that and convert it into an actual response object.

Use case: all of our routes return dicts, which we serialize to JSON through a decorator. We have no non-JSON routes. I'd like to remove our decorator and make this change application-wide instead.

**Comment by RonnyPfannschmidt** [comment]
for that purpose you are supposed to override `Flask.make_response` or use a custom response class

since you always want to return dicts, you could just set the response class of your app to a JsonResponse that does the encoding

**Comment by SirCmpwn** [comment]
>for that purpose you are supposed to override Flask.make_response or use a custom response class

Monkey patching is lame if a different solution is possible.

>since you always want to return dicts, you could just set the response class of your app to a JsonResponse that does the encoding

Yeah, this is possible, but I don't see why we can't have after_request deal with it. It seems like a pretty reasonable place. I also had a look through the relevant code, and it wouldn't be too difficult to make it work.

Side note, I changed the title of this issue to fix a mistake.

**Comment by ThiefMaster** [comment]
Overriding a method is not monkeypatching.

**Comment by SirCmpwn** [comment]
How do you "override" it?

**Comment by ThiefMaster** [comment]
```
class MyFlask(Flask):
    ...
```

**Comment by SirCmpwn** [comment]
Ah, I see. I could indeed do that, but I think that's a bit drastic, since now the Flask imported from flask will not behave correctly and several modules (and maybe even vendor modules) risk being broken.

**Comment by ThiefMaster** [comment]
You usually only import `Flask` once in your application; in whatever place you use to create your app object. So there should be only once place where you need to use the custom object.

It's also explicitly encouraged to subclass Flask: http://flask.readthedocs.org/en/latest/becomingbig/#subclass

**Comment by SirCmpwn** [comment]
Good to know. So there are several ways of addressing this problem, then - but does that mean that this feature is not valuable? The decorator can be used several times and the response object can be repeatedly transformed (also via vendor libs, potentially) if we went this route.

**Comment by davidism** [comment]
Agreed, if you need to handle another type of return value from every view, override `make_response`.

~~~python
class MyFlask(Flask):
    def make_response(self, rv):
        if isinstance(rv, dict):
            return make_a_response_from_this_dict(rv)
        return super().make_response(rv)
~~~

`after_request` is for modifying the `Response` object, not the data specifically.  You can still modify the data, you just need to parse it out and re-apply it.  There's no general way to handle `after_request` functions returning other data, as the next function in the change wouldn't know what to expect.
