### ISSUE TITLE
an context confuse when i using the celery 

### ISSUE THREAD

**Issue by Smalinuxer** [mitsuhiko/flask#1576]
it appear in when i using the celery with flask_sqlalchemy 

i am using the celery with context  by  http://flask.pocoo.org/docs/0.10/patterns/celery/
but i find "copy_current_request_context" is not work , because the context is typeof the AppContext not the RequestContext . so when invoke @copy_current_request_context , it raise the 

RuntimeError('This decorator can only be used at local scopes '
            'when a request context is on the stack.  For instance within '
            'view functions.')

so i try to  replace the RequestContext with AppContext in @copy_current_request_context , it work!
the code which i changed ( from flask/ctx.py ): 

    def copy_current_request_context(f):

        top = _app_ctx_stack.top
        if top is None:
            raise RuntimeError('This decorator can only be used at local scopes '
                'when a request context is on the stack.  For instance within '
                'view functions.')
        reqctx = top.copy()
        def wrapper(*args, **kwargs):
            with reqctx:
                return f(*args, **kwargs)
        return update_wrapper(wrapper, f)

    class AppContext(object):

        def __init__(self, app):
            self.app = app
            self.url_adapter = app.create_url_adapter(None)
            self.g = app.app_ctx_globals_class()

            # Like request context, app contexts can be pushed multiple times
            # but there a basic "refcount" is enough to track them.
            self._refcnt = 0

        def copy(self):
  
            mapp = self.__class__(self.app,)
            return mapp

        def push(self):
            """Binds the app context to the current context."""
            self._refcnt += 1
            _app_ctx_stack.push(self)
            appcontext_pushed.send(self.app)

        def pop(self, exc=None):
            """Pops the app context."""
            self._refcnt -= 1
            if self._refcnt <= 0:
                if exc is None:
                    exc = sys.exc_info()[1]
                self.app.do_teardown_appcontext(exc)
            rv = _app_ctx_stack.pop()
            assert rv is self, 'Popped wrong app context.  (%r instead of %r)' \
                % (rv, self)
            appcontext_popped.send(self.app)

        def __enter__(self):
            self.push()
            return self

        def __exit__(self, exc_type, exc_value, tb):
            self.pop(exc_value)

**Comment by Smalinuxer** [comment]
i think it not reasonable to copy_current_request_context using the RequestContext
cause in other thread in gevent it also use the ormaping not the request or something

by the way . i use the celery to merge the data from mongo to mysql .

**Comment by davidism** [comment]
You can only use that decorator within an app context, since it relies on an app context being present.  I'm not clear where you even got that code from.  The whole point of the code in the docs is so that the workers will execute tasks in an app context without having to pass it explicitly.  If your task requires information from the request, pass it manually rather than trying to copy the request context.

**Comment by Smalinuxer** [comment]
@davidism 
中文 : 这代码是我改的,ctx.py , 你说的完全是瞎鸡巴回的.

this code is from ctx.py which i changed , before i changed , the decorator require the request context , but i only get the app context from the docs . so you know nothing about  it

**Comment by Smalinuxer** [comment]
@davidism 
are you serious?
you don't understand my question and you talk about bullshit, now you close my question?

so fuck you !
you mother fucker !

**Comment by ThiefMaster** [comment]
Seriously? You couldn't even be bothered to format all your code properly and post a rather unclear issue and then start insulting people?
