### ISSUE TITLE
Make SEND_FILE_MAX_AGE_DEFAULT support datetime.timedelta

### ISSUE THREAD

**Issue by fnkr** [mitsuhiko/flask#1580]
`SEND_FILE_MAX_AGE_DEFAULT` should support `int` or `datetime.timedelta`, like `PERMANENT_SESSION_LIFETIME` does.

http://flask.pocoo.org/docs/0.10/config/#builtin-configuration-values

**Comment by fnkr** [comment]
Hi,

can I ask when v0.11 will be released?

**Comment by davidism** [comment]
We are working towards the 1.0 release, but there is no set date yet.
