### ISSUE TITLE
Enable distribution as a standalone, compiled executible with nuitka

### ISSUE THREAD

**Issue by datnamer** [mitsuhiko/flask#1582]
http://nuitka.net/pages/overview.html

Thoughts?

**Comment by hbrls** [comment]
I'm working on building a [docker image](https://github.com/hbrls/docker-flask-app).

**Comment by davidism** [comment]
What needs to be done on Flask's side to make this happen?  I'm not clear, just from reading the blurb.  A better way forward would be for someone who wants it to give it a try, and if there are bugs related to Flask then post them.

**Comment by khusseini** [comment]
@datnamer were you successful in compiling a flask application with nuitka?
