### ISSUE TITLE
in pluggable views, why not passing url variable parameters to view object?

### ISSUE THREAD

**Issue by ethe** [mitsuhiko/flask#1590]
in flask doc's giving examples, the view would look like this:
```python
class UserAPI(MethodView):

    def get(self, user_id):
        if user_id is None:
            # return a list of users
            pass
        else:
            # expose a single user
            pass

    def post(self):
        # create a new user
        pass

    def delete(self, user_id):
        # delete a single user
        pass

    def put(self, user_id):
        # update a single user
        pass
```
why not make it like this?
```python
class UserAPI(MethodView):

    def __init__(self, user_id):
        self.user_id = user_id

    def get(self):
        if self.user_id is None:
            # return a list of users
            pass
        else:
            # expose a single user
            pass

    def post(self):
        # create a new user
        pass

    def delete(self):
        # delete a single user
        pass

    def put(self):
        # update a single user
        pass
```
the first way seems not simple and direct.

**Comment by davidism** [comment]
That's not how these class based views were designed.  The `View` classes are *factories*, they're instantiated to create views, not to handle them.  This means you could create an `__init__` method that customizes what the views do.  For example, you could have a `APIView` that takes a model, so a common set of views could be applied to different models, `APIView.as_view(User)`.  That's not to say that you couldn't design a class that does what you want instead, but that's not what these were designed for.

**Comment by ethe** [comment]
thanks.
