### ISSUE TITLE
[Document Bug] get_json(force=False, silent=False, cache=True)

### ISSUE THREAD

**Issue by huntzhan** [mitsuhiko/flask#1612]
Parameters:	

    force – if set to True the mimetype is ignored.
    silent – if set to False this method will **NOT** fail silently and return False.
    cache – if set to True the parsed JSON data is remembered on the request.

http://flask.pocoo.org/docs/0.10/api/#flask.Request.get_json

**Comment by SBillion** [comment]
To keep the same logic as other parameter description, we should have:


> silent – if set to **True** this method will fail silently and return False.

**Comment by huntzhan** [comment]
Furthermore, `get_json` would return `None` instead of `False` in the case of failing silently.

**Comment by davidism** [comment]
Already fixed in [master][1].  Due to the way docs are built, this cannot be fixed in the 0.10 docs.

[1]: https://github.com/mitsuhiko/flask/blob/master/flask/wrappers.py#L133
