### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor for python3 + flask

### ISSUE THREAD

**Issue by hongy19** [mitsuhiko/flask#1617]
I got following error with flask (0.10.1) + python 3.5. But python 2.7 is OK.
If I turn off debug flag, python 3.5 is also OK. 
Werkzeug (0.11) works well with/with out debug flag for python 3.5

C:\tmp\flask>py -3 test1.py
Traceback (most recent call last):
  File "test1.py", line 13, in <module>
    app.run()
  File "C:\Python35\lib\site-packages\flask\app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "C:\Python35\lib\site-packages\werkzeug\serving.py", line 666, in run_simple
    os.set_inheritable(s.fileno(), True)
OSError: [Errno 9] Bad file descriptor

Flask code
from flask import Flask
app = Flask(__name__)
app.debug = True
@app.route("/")
def index():
    return "Hello world!"
if __name__ == '__main__':
    app.run()

Werkzeug code
from werkzeug.wrappers import Request, Response
from werkzeug.debug import DebuggedApplication
@Request.application
def application(request):
    return Response('Hello World!')
application =  DebuggedApplication(application, evalex=True)
if __name__ == '__main__':
    from werkzeug.serving import run_simple
    run_simple('localhost', 4000, application)

**Comment by mitsuhiko** [comment]
This is fixed in latest version of Werkzeug that will release today.
