### ISSUE TITLE
Flask extremely slow on SQL Server view queries versus pure table queries

### ISSUE THREAD

**Issue by erxnmedia** [mitsuhiko/flask#1619]
Hi,

I’ve noticed that Flask takes 10 or 20 seconds to display a page based on a view query but will display the page in less than a second for a non-view version of the same query.  For example here is a query on view CurveVersionReport:

select CurveEditID,AsOfDate,TaskDefinition,VersionName,acattribute,DataPoints
FROM CurveVersionReport
where market = 'Commodity' and submarket = 'Agriculture' and activeversion='Yes' and curvename='CO_PRICE_VAR_USD_OTC_BO'
order by curvename, curveeditid

and the corresponding non-view version:

select a.[CurveEditID],[AsOfDate],TaskDefinition     
      ,[CurveVersion] as VersionName
	  , tree + '.' + attribute as acattribute 
	  ,count(*) AS DataPoints
  FROM [CurveEdits] a, curvedefinition b, submarket c, TaskDefinition d, curveversion e, curvepoints f, acattribute g
  where a.curveid = b.curveid 
  and b.marketid = c.marketid
  and a.TaskDefinitionID=d.TaskDefinitionID
  and a.[CurveVersionID]=e.[CurveVersionID]
  and f.curveeditid = a.curveeditid
  and f.acattributeid = g.acattributeid
  and market = 'Commodity' and submarket = 'Agriculture' and activeversion=1 and curvename='CO_PRICE_VAR_USD_OTC_BO'
  group by market, submarket, curvename, a.[CurveEditID],[AsOfDate],TaskDefinition,[CurveVersion],[ActiveVersion], tree, attribute 
  order by acattribute

This is the Flask method that processes the query:

@app.route('/curve/<market>/<submarket>/<curve>')
def Curve(market, submarket, curve):
    global cur
    query = ...one of the above
    cur.execute(query, (market, submarket, curve))
    edits=[x for x in cur.fetchall()]
    return render_template('curve.html', market=market, submarket=submarket, curve=curve, edits=edits)

Here is the template file:

<h5><img src='/static/wf_logo_50px.png'> 
<a href="/" target="_blank_">PFE Analytics:</a>
<a href="/Markets" target="_blank_">Market:</a> 
<a href="/market/{{market}}" target="_blank_">Submarket:</a>
<a href="/submarket/{{market}}/{{submarket}}" target="_blank_">Curve:</a>
{{market}} {{submarket}} {{curve}}</h5>

<table border="1">
<tr>
<th>CurveEditID</th>
<th>AsOfDate</th>
<th>TaskDefinition</th>
<th>VersionName</th>
<th>acattribute</th>
<th>DataPoints</th></tr>

{% for (CurveEditID,AsOfDate,TaskDefinition,VersionName,acattribute,DataPoints) in edits %}
<tr>
<td>{{CurveEditID}}</td>
<td>{{AsOfDate}}</td>
<td>{{TaskDefinition}}</td>
<td>{{VersionName}}</td>
<td>{{acattribute}}</td>
<td>{{DataPoints}}</td></tr>
{% endfor %}

</table>

Do you know why view version would be extremely slow versus non-view?

Thanks, 

Lars Ericson

Quantitative Analytics Consultant
Market & Institutional Risk Management 

Wells Fargo Bank, N.A. | 301 S. College St., 4th Floor | Charlotte, NC 28202-6000
MAC D1053-04X
Tel  704-410-2219 | Cell 917-891-1639

lars.ericson@wellsfargo.com

**Comment by mitsuhiko** [comment]
This is an issue tracker and not a support forum.  Flask does not contain any database functionality out of the box and it would appear your issue is entirely unrelated to database drivers anyways and caused by your database system.

Please bring questions like this up on stackoverflow or similar forums.

**Comment by erxnmedia** [comment]
actually that was helpful: http://www.sommarskog.se/query-plan-mysteries.html
