### ISSUE TITLE
xss issue

### ISSUE THREAD

**Issue by linuzzz** [mitsuhiko/flask#1620]
Hello, i'm using this repository to start learning python + flask.
I red that flask with the help of jinja2 should escape any sql injection or xss attack.
Anyway if i start using the flaskr app in the examples i see that it is possible to inject xss code, i did a simple test with [<script>alert"hello"</script> ohh...github doesn't show the code of the alert] and it's working...it's a permanent xxs because it is written in the db. I would like to start writing secure code from the beginning, someone could explain how to avoid xss in this simple app? many thanks

**Comment by mitsuhiko** [comment]
Can you please be more concrete?  You can embed code on github this way:

    ```
    code goes here
    ```

**Comment by mitsuhiko** [comment]
Oh. You are referring to the `flaskr` application.  This one intentionally allows embedding HTML.  It's operating in a trusted environment.  It uses the `|safe` filter to explicitly disable the default escaping.  Just don't use that if you don't want HTML embedded.

**Comment by linuzzz** [comment]
many thanks! i removed |safe from the template and the xss is filtered out!
