### ISSUE TITLE
demo doesn't show the active port

### ISSUE THREAD

**Issue by llimllib** [mitsuhiko/flask#1623]
On python 3.4.3 with `flask-0.10.1`, running the demo in the [quickstart](http://flask.pocoo.org/docs/0.10/quickstart/) doesn't print what port it's on:

```
$ python helloworld.py
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 281-051-764
```

it is on port 5000, so you can guess it from the docs, but I think it should tell the user what port it's running on?

**Comment by mitsuhiko** [comment]
That seems to be a regression in Werkzeug on Python 3.  I will open an issue in the correct tracker.

**Comment by llimllib** [comment]
Thanks, and sorry for opening it was n the wrong project
