### ISSUE TITLE
Links to download documentation need updating

### ISSUE THREAD

**Issue by errata9** [mitsuhiko/flask#1635]
First, the link to the docs on the main page:

    http://flask.pocoo.org/docs/

is missing the links on the left for downloading the docs. It should be:

    http://flask.readthedocs.org/en/latest/

Second, the download links on the left are dead ends:

    http://flask.pocoo.org/docs/flask-docs.[epub,pdf,mobi,zip]

should be:

    http://readthedocs.org/projects/flask/downloads/[pdf,epub,htmlzip]/latest/

Same thing for the docs download links on the main page under the heading "Interested?"

**Comment by davidism** [comment]
The readthedocs version is not an official source of documentation.  The links are indeed broken on the official site, but that belongs under either pocoo/metaflask#7 or pocoo/metaflask#43 or mitsuhiko/flask-website#16.
