### ISSUE TITLE
Open Redirect Vulnerability  

### ISSUE THREAD

**Issue by RaminFP** [mitsuhiko/flask#1639]
Hi,

Code:
```
from flask import Flask
from flask import request

app = Flask(__name__)
@app.route('/',methods=['GET', 'POST'])
@app.route('/name')
def index(name=""):

    #name = request.args.get('name',name)
    return  "hello %s " % name

@app.route('/')
def home():

    return "home page"


app.run(debug=True,port=8000,host='0.0.0.0')
```
i using url http://127.0.0.1:8000/ and it's work , now using http://127.0.0.1:8000//google.com open redirect issue to google.com, but using http://127.0.0.1:8000///google.com get error not found,

**Comment by wlhlm** [comment]
As the [documentation](http://flask.pocoo.org/docs/0.10/deploying/#deployment) states the integrated server is intended __for development environments only__:
> Depending on what you have available there are multiple ways to run Flask applications. You can use the builtin server during development, but you should use a full deployment option for production applications. (Do not use the builtin development server in production.) Several options are available and documented here.

This doesn't seem like an issue to me, or does this happen with other servers as well (gunicorn, uwsgi, etc.)?

**Comment by RaminFP** [comment]
any test with other server but i run server flask work this issue ,, using code above and run server an any check validation url , 
Request :
## GET //google.com HTTP/1.0
```
Host: 127.0.0.1:8000
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
Cookie: csrftoken=v9WXXZW8uDWz7XrarUBqmZdH1drdWErD
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36

HTTP/1.0 301 MOVED PERMANENTLY
Content-Length: 243
Content-Type: text/html; charset=utf-8
Date: Sat, 05 Dec 2015 19:17:30 GMT
Server: Werkzeug/0.11.2 Python/2.7.10
```
## Location: http://google.com/



GET / HTTP/1.1
Host: google.com
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
Cookie: PREF=ID=1111111111111111:FF=0:LD=en:TM=1446740391:LM=1446740590:GM=1:V=1:S=bvrh0iJSlDPfDRcm; HSID=A-RWO0xT0s-nF2oZZ; APISID=vdJAmppxhi_CMLCt/Af_PAw9M7_IGr6RNZ; SID=DQAAACABAAAvvyatOpvJoggRTBvHH5GR3Y_H8Wt6nwYv6ofWOlggT5ZHjeOPn_0sAUzzt5N5Pl4JjB-JorMQWb-DCcc0zW0dJ8nk5H6i2UPDZqreIPFmbCzlOflvGprvnqs1lWsRM_G80yqPllj_9rwoDwSM1hnZOdyBWVKl35xZ9uzSOWbYWTxskIL_eMIl_2QNVx19cjQvG3_pDgITPG8BUCtH0ssh157iq0eZ2vrufgKBBvXI6V2XD4INK0-dUmmBve736aaknl2F0YiXFDyseCDpt2UIic3Sr9sz0AP7Ii5vjwkMYxDvzojydebuxMOiAcdTrD1lfO4PrpSQEZiFhOKr2Gjko5OUO5T1rW4kVDEZA9fSHBNNVUcg92iDEfEXNlg9ZrM; NID=74=BDFEAdVHJvHDMRIRd9sFoMfDkdTmzmqYazWGe2d1_JUmenhx-TBsrMTOQ0VMpnXsO3rofrG1U2PwyQhNX_bVimqc_bNptfFKL0H8zFoCq4aLSco4Y3843bc09cqwNoYyQE15BSoC81VQVEsjgqol0Qn-rkiFiyiys-LKbW0jqb9OMlPPgRawh3wqec0cJlHE8iiRxa54YW7QD_t3sPYApMIqPJKcVU6otl5YPUitkPJhuzO-ZDjkClsJXVaUKAbDwVWmawr1FAjsAsS3m8beMGZw
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36

HTTP/1.1 301 Moved Permanently
Cache-Control: public, max-age=2592000
Content-Length: 219
Content-Type: text/html; charset=UTF-8
Date: Sat, 05 Dec 2015 19:18:00 GMT
Expires: Mon, 04 Jan 2016 19:18:00 GMT
Location: http://www.google.com/
Server: gws
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
```

**Comment by RaminFP** [comment]
Flask can not prevent all open redirects attacks automatically?

**Comment by davidism** [comment]
There are no redirects in the sample code you've shown.  You can't go to that url because you didn't define a route that matches it.

**Comment by RaminFP** [comment]
i don't understand , here test for you : http://148.251.25.244:9090//gooogle.com

**Comment by davidism** [comment]
This appears to be some quirk of the debug server, which is provided by Werkzeug, not Flask.  Running with a production app server (gunicorn) does not have this issue.

**Comment by davidism** [comment]
Actually, this appears to be a Firefox bug.  I can't reproduce the issue in Chrome, but navigating to http://127.0.0.1:5000//google.com *even when no server is running* redirects to Google in Firefox.  Running the server in a debugger, no breakpoints are even triggered.

**Comment by RaminFP** [comment]
No @davidism , i test to firefox , chrome , Opera and redirect to google.com and other site bing.com , yahoo.com , msn.com redirect to other domains . i ready dispay to you in video for this issue,

```
Running the app with gunicorn prevents this as well.
```
ok, but you see this bug exist in flask on two slash "//" redirect to other site , if user run flask web application on VPS server and run service on OS linux/mac  without using other web server,
this issue cause attack phishing,

**Comment by ThiefMaster** [comment]
You are not supposed to do that. Open redirects are mostly an issue on 
high-profile/trusted sites and those are even less likely to use the dev 
server in production.

@davidism: 301 redirect maybe? That'd explain why it happens for you with 
no server running.

**Comment by RaminFP** [comment]
@ThiefMaster  ```those are even less likely to use the dev server in production.```

i say : run service Linux/Mac with bash and call python code and access to web application flask,
example Now : http://148.251.25.244:9090//google.com

**Comment by ThiefMaster** [comment]
The dev server is not acceptable for any production setup, period. If someone uses it anyway, it's his fault if his box gets pwned or abused.

I just looked into it and the problem happens due to an incorrect `SERVER_NAME` being passed to the werkzeug from the dev server (it's set to `google.com` when using the two slashes)

**Comment by RonnyPfannschmidt** [comment]
can someone still report a bug to werkzeug perhaps so it can decide on how to handle this?

**Comment by ThiefMaster** [comment]
OK, this is not a flask bug, possibly not even a werkzeug bug. `BaseHTTPRequestHandler` (python stdlib) doesn't normalize consecutive slashes into a single one so it passes a path of `//google.com` to the dev server which runs this code:

    request_url = url_parse(self.path)

The double slash results in the `netloc` being set instead of the `path` so eventually it does end up in `HTTP_HOST`.

**Comment by RaminFP** [comment]
your means issue here @ThiefMaster : 
```
class WSGIRequestHandler(BaseHTTPRequestHandler, object):
    """A request handler that implements WSGI dispatching."""

    @property
    def server_version(self):
        return 'Werkzeug/' + werkzeug.__version__

    def make_environ(self):
        request_url = url_parse(self.path) ### issue here? 
```
https://patreon.thecthulhu.com/extracted/patreon.tar.gz/venv/lib/python3.4/site-packages/werkzeug/serving.py

**Comment by ThiefMaster** [comment]
Yes. `self.path` it set in the Python stdlib and contains `//google.com` in your case. 
Later it's used to populate HTTP_HOST: https://github.com/mitsuhiko/werkzeug/blob/master/werkzeug/serving.py#L129-L130 (please.. use the proper repo when linking to code, not some leak that just happens to contain a copy of a virtualenv containing werkzug)

**Comment by davidism** [comment]
Ultimately, the answer is still the same: don't use the dev server in production, it is not designed to be secure.  At this point, it's clear that this is not a Flask bug, and it has been reported in mitsuhiko/werkzeug#822.  Closing.

**Comment by RaminFP** [comment]
I know, I just define a senaro and this id not good idea for redirect,  and now display issue here of HTTP_HOST ,
and I will happy for fix this issue here :
