### ISSUE TITLE
template loaders configuration don't support zipped applications

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [mitsuhiko/flask#1645]
based on #1562

due to using a filesystem-loader instead of a package-loader, egg based installs and zipped python applications as well as compressed wheels in the pythonpath can not load templates

the problem lies in `_PackageBoundObject` not using a package loader,
i don't recall if this was done for performance or due to other downsides

**Comment by alexpantyukhin** [comment]
But `PackageLoader` works only with package as I see. Maybe it would be okay to have some another option (something like `template_package`) and if it None use the approach with `FileSystemLoader`?

**Comment by RonnyPfannschmidt** [comment]
well, any non single file app is usually in a package - so i dont see a huge problem there

**Comment by mitsuhiko** [comment]
@RonnyPfannschmidt mainly was done because `/static` breaks anyways. So it does not help if we can ship packages but not static files.

**Comment by RonnyPfannschmidt** [comment]
closing as wont fix then, should this be documented somewhere?
