### ISSUE TITLE
Injecting Flask vulnerability issue

### ISSUE THREAD

**Issue by rmetzler** [mitsuhiko/flask#1656]
On December 7, 2015 Ryan Reid published a blog post  called ["Injecting Flask" ](https://nvisium.com/blog/2015/12/07/injecting-flask/).

In his post he demonstrated several attacks against a naive Flask / Jinja2 based implementation of a website.

I'm not sure if Flask has documented best practices which would mitigate the problem and I couldn't find any hint of a discussion of his blog post in the Flask community.

Are there plans to fix or document the problem?

For me it's a rather minor thing because I only have one internal service which depends on Flask, but I'm sure other developers may have many more and this is a serious security issue.

**Comment by rmetzler** [comment]
This adds a little bit more to the discussion: https://www.reddit.com/r/netsec/comments/3vu7ii/injecting_flask_blogpost/

**Comment by jirikuncar** [comment]
> `template = '''<h2>Hello %s!</h2>''' % person['name']`

I have stopped reading after first example which is not correct and it should be `template = '''<h2>Hello {{ person.name }}</h2>'''` :wink:

**Comment by ThiefMaster** [comment]
Yeah, that whole blog post is rather :hankey:-y. TL;DR is "don't be an idiot and use Flask properly". Just like you shouldn't use `%` interpolation with a DBAPI...

> `<a href='{{ url_for('hello_xss')}}?name={{ name |e}}'>...</a>`

That's not even secure, since you are supposed to use double quotes for tags with dynamic data. And building the query string manually after `url_for`? Really?

**Comment by davidism** [comment]
"Look what happens if I ignore all the built in mechanisms that protect me" is not a useful method for discussing vulnerabilities. All these mechanisms, at least those related to Flask, are discused throughout the docs.
