### ISSUE TITLE
COC?

### ISSUE THREAD

**Issue by alison985** [mitsuhiko/flask#1660]
Hi,

I'm just wondering what your code of conduct is for this project?

Thanks,
Alison

**Comment by mitsuhiko** [comment]
This project does not need one. Decent behaviour can be enforced without one.

(Aside: please do not use the issue tracker for asking questions)

**Comment by ThiefMaster** [comment]
Seriously? Is "have common sense and don't be a dick/asshole" without being written down not enough?

**Comment by ThiefMaster** [comment]
All the time spent on posting the same issue in [so many repos](https://cloud.githubusercontent.com/assets/179599/11917995/ba611f5e-a71e-11e5-87d2-5ed0db67abe9.png)... you could have contributed useful code or documentation to many of those projects instead :)

Most people know how to act without having something written don. "Don't be a dick" is part of having common sense.

**Comment by mitsuhiko** [comment]
Let's not drag out this issue.
