### ISSUE TITLE
multiple processes on windows

### ISSUE THREAD

**Issue by samlobel** [mitsuhiko/flask#1662]
It looks like deep down, Flask calls `SocketServer.py` (a source code file for Python) to make its server.  But `SocketServer.py` has a call to `os.fork()`, which isn't supported at all on Windows. It would be great to use something besides `SocketServer`, or maybe a modified version of `SocketServer`.  When you make a HTTP request, it first calls `SocketServer.process_request`, which then calls `os.fork`.

More importantly (to me at least), does anyone have a workaround?

**Comment by davidism** [comment]
This is more related to Werkzeug, not Flask, but just use uWSGI, Gunicorn, or another production WSGI server.  The actual issue should be taken up with Python, as `ForkingMixin` is part of the standard library and is hard coded to use `os.fork`.  [It looks like you already reported it.](https://bugs.python.org/issue25931)
