### ISSUE TITLE
OPTIONS default behavior not compatible with Angularjs

### ISSUE THREAD

**Issue by galgalesh** [mitsuhiko/flask#1664]
Hi

When calling a flask webserver from angularjs, you get `method not allowed` and `content-type not allowed` errors. This is because the flask OPTIONS response does not specify `Access-Control-Allow-Headers` and `Access-Control-Allow-Methods` by default.

This is fixed by following code fragment:

```
@app.after_request
def apply_caching(response):
    response.headers['Access-Control-Allow-Headers'] = 'Content-Type'
    response.headers['Access-Control-Allow-Methods'] = 'GET,PUT'
    return response
```

Is the exclusion of these headers intentional or is this a bug? I think a lot of people call Flask from angularjs, so supporting these headers by default might be good for adoption and ease of use?

Kind regards

**Comment by ThiefMaster** [comment]
You only need those headers for CORS (cross-origin/domain requests).

**Comment by galgalesh** [comment]
Thanks for this explanation, I did not realize this was the case.

I suspect enabling CORS by default poses a security risk?

**Comment by ThiefMaster** [comment]
Yes. Also, it shouldn't be needed at all unless you intend to access your endpoints with AJAX calls from a different host/port. And in that case, you'd include another of those headers to specify which hosts are actually allowed to send requests.

**Comment by galgalesh** [comment]
Thanks for this explanation. I knew about the `Access-Control-Allow-Origin` header and I currently set this to allow the web server to access the REST API. I did not realize the other `Access-Control-Allow-*` headers also had to do with CORS.

Closing this as the bug is invalid.
