### ISSUE TITLE
When I run 'pip install Flask' in Ubuntu server I got these info

### ISSUE THREAD

**Issue by ShiWeiCN** [mitsuhiko/flask#1665]
error: could not create '/usr/local/lib/python2.7/dist-packages/flask': Permission denied

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_habit/Flask/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Dy8fke-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_habit/Flask
Storing debug log for failure in /home/habit/.pip/pip.log

**Comment by jos666** [comment]
error: could not create '/usr/local/lib/python2.7/dist-packages/flask': Permission denied   权限拒绝 
没权限创建目录

**Comment by davidism** [comment]
Do not use pip to install to the system (sudo). Use a virtualenv.
