### ISSUE TITLE
WERKZEUG_DEBUG_PIN

### ISSUE THREAD

**Issue by RogerHaase** [mitsuhiko/flask#1687]
Werkzeug 0.11.0 implements WERKZEUG_DEBUG_PIN.

imho, the problem is this code:

    class Server(Command):
        """
        Runs the Flask development server i.e. app.run()

        :param host: server host
        :param port: server port
        :param use_debugger: if False, will no longer use Werkzeug debugger.
                             This can be overriden in the command line
                             by passing the **-d** flag.
        :param use_reloader: if False, will no longer use auto-reloader.
                             This can be overriden in the command line by
                             passing the **-r** flag.
        :param threaded: should the process handle each request in a separate
                         thread?
        :param processes: number of processes to spawn
        :param passthrough_errors: disable the error catching. This means that the server will die on errors but it can be useful to hook debuggers in (pdb etc.)
        :param options: :func:`werkzeug.run_simple` options.
        """

        help = description = 'Runs the Flask development server i.e. app.run()'

        def __init__(self, host='127.0.0.1', port=5000, use_debugger=True,
                     use_reloader=True, threaded=False, processes=1,
                     passthrough_errors=False, **options):

            self.port = port
            self.host = host
            self.use_debugger = use_debugger
            self.use_reloader = use_reloader
            self.server_options = options
            self.threaded = threaded
            self.processes = processes
            self.passthrough_errors = passthrough_errors

... where the defaults for use_debugger and use_reloader should be False and passing the -d,-r flags should turn the debugger and auto reloader on..

**Comment by ThiefMaster** [comment]
What exactly is the problem?
