### ISSUE TITLE
Make it easier to get a response body string in python3

### ISSUE THREAD

**Issue by anlutro** [mitsuhiko/flask#1690]
In py3, `response.data` returns a byte value, meaning you can't do `if 'foo' in response.data` in tests, for example.

Currently, the best way to get the response body as a string seems to be `response.get_data(as_string=True)`, which is a bit tedious.

Maybe add a `response.text` property? That's what the requests package seems to have done.

**Comment by mitsuhiko** [comment]
Instead of doing that I recommend doing if b'foo' in response.data. I already am not a fan of `as_string=True` in the get data call.  It just fundamentally makes no sense to operate on text there.

**Comment by anlutro** [comment]
What if I need to run assertions on non-ASCII values? I'd appreciate it if I could do `if 'wørd' in response.text` regardless of whether the response was encoded in UTF-8 or ISO-8859-1 (assuming it has the correct Content-Encoding header, of course).

**Comment by ThiefMaster** [comment]
is that really such a common use-case? i think it'd be much easier to simply add a `response_to_text` util that decodes the bytes using the encoding in the response's content-type header

**Comment by anlutro** [comment]
That's what I'm doing already, but because it seemed like such an obvious feature, I saw no reason not to suggest it upstream.
