### ISSUE TITLE
Built-in support for reverse proxying on a sub folder

### ISSUE THREAD

**Issue by ericremoreynolds** [mitsuhiko/flask#1695]
Hello,

It's annoying to have to reimplement [this snippet](http://flask.pocoo.org/snippets/35/) for every web app in order for `url_for` to work properly behind an nginx reverse proxy mounted on a sub folder of the host's root URL.

Could the not the functionality not be built into Flask by default?

Sorry for opening an issue instead of a PR, I don't think I have the expertise to modify Flask's code base.

Regards,

Eric.

**Comment by ThiefMaster** [comment]
Instead of adding it to Flask I think it'd rather make sense to include it as a wsgi middleware in werkzeug just like e.g. ProxyFix

**Comment by davidism** [comment]
Yeah, that belongs in Werkzeug, although I'm not sure how willing we are to add new middleware.
