### ISSUE TITLE
Unicode with request.path & url_for('auth.index')

### ISSUE THREAD

**Issue by psykzz** [mitsuhiko/flask#1697]
Commonly i do a check similar to

```python
if request.path != url_for('auth.index'):


```

The issue with this on Python3.5 right now is that request.path is unicode while url_for is a string.

```python
print(request.path, url_for('auth.index'))
>>> (u'/auth/', '/auth/')
```

Is this intended or is there a reason for it? Could we not have both return unicode?

**Comment by ThiefMaster** [comment]
For this specific use-case you should do `request.endpoint == 'auth.index'`

**Comment by psykzz** [comment]
Thanks for the advice @ThiefMaster, that does make more sense.

I also fixed my issue as a weird linking issue with uwsgi and my venv.
uwsgi was picking up 2.7 and causing weird issues. 

A reinstall, removing from system-site and putting it fresh into my venv worked fine.
