### ISSUE TITLE
Traceback returns KeyError: WERKZEUG

### ISSUE THREAD

**Issue by Sujinthan** [mitsuhiko/flask#1699]
When I send an item to my server I get this error:

    Traceback (most recent call last):
      File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 648, in inner
        fd = int(os.environ['WERKZEUG_SERVER_FD'])
       File "C:\Python27\lib\os.py", line 425, in __getitem__
        return self.data[key.upper()]
     KeyError: 'WERKZEUG_SERVER_FD'
    - - [23/Jan/2016 22:19:33] "POST / HTTP/1.1" 500 -

Can't seem to figure out why. I am sending the item to the server as a base64. I should note that I am sending an image as a base64

**Comment by untitaker** [comment]
Please provide an example that fails.

**Comment by Sujinthan** [comment]
Sorry, I got it working, there was an error on the client side.
