### ISSUE TITLE
Duplicate key in jsonify

### ISSUE THREAD

**Issue by vietvudanh** [mitsuhiko/flask#1726]
Hi, I was following the tutorial on Flask at [this](http://flask.pocoo.org/docs/0.10/tutorial/).
And I tried to return json data so I use `jsonify`

I found out that jsonify use `dict()` to convert params into a dict. But this will remove items with duplicate key.

In my case, I querried the data using this query

`cur = g.db.execute('SELECT title, text from entries order by id desc')`

The data was:

`[(u'Nope', u'hi, this is anoooother things'), (u'Nope', u'This is another'), (u'Hi', u'This is a sample entry')]`

So the jsonify just return:

`{
  "Hi": "This is a sample entry", 
  "Nope": "This is another"
}`

The code work correctly, but I don't know if this is intended or not?

**Comment by jaapz** [comment]
Apart from the fact that I think it's a really bad idea to have duplicate keys in a json object, according to [this](http://stackoverflow.com/a/19927061) stackoverflow answer, it technically is not invalid to have duplicate keys in json. However it's not specified how an encoder/decoder should handle duplicate keys. However, generally the implementations don't allow for duplicate keys. This is the case in most browsers as far as I know. So I think `jsonify`'s implementation is correct here.

**Comment by vietvudanh** [comment]
Yes, I know that having duplicate keys is not valid.
I just think that like in this case: there might be situation that the returned data might have duplicate keys, but actually they are different items.

And btw, I have misunderstood the usage of `jsonify`. The data needs to be a dict, not list. I just have read the security note about `jsonify`. 

`For security reasons only objects are supported toplevel.  For more
    information about this, have a look at :ref:'json-security'.`

The implementation was correct.
