### ISSUE TITLE
You may want to include this example base Docker image with uWSGI and Nginx in the docs

### ISSUE THREAD

**Issue by tiangolo** [mitsuhiko/flask#1734]
I made a public (and open source) Docker image that you can use to build a Python Flask web application.

It has uWSGI for running the application, Nginx to serve HTTP and Supervisord to control them, so you don't have to learn how to install and configure all those to build your Python Flask web app.

It seems like uWSGI with Nginx is one of the more robust (and with great performance) ways to deploy a Python web app. Here are the benchmarks: <http://nichol.as/benchmark-of-python-web-servers>.

If there was an official Flask Docker image for deployment I would like to use it. But then, if there was an open source performant Docker image that could help deploying an app without having to learn, install and configure uWSGI, Nginx, Supervisord, I would have liked to find it in your docs. 

Now that I built this one, you may want to include it in your docs, maybe as "a third party example" or something. If you think this could be useful, I could submit a PR.

I think it could be in **deploying**: <http://flask.pocoo.org/docs/0.10/deploying/>
Or in snippet category **deployment**: <http://flask.pocoo.org/snippets/category/deployment/>

There are even some template projects you can use to bootstrap your own. And also, you don't have to clone the full project or something, you can just use it as a base image.

Docker Hub: <https://hub.docker.com/r/tiangolo/uwsgi-nginx-flask/>
GitHub: <https://github.com/tiangolo/uwsgi-nginx-flask-docker>

**Comment by hbrls** [comment]
I have a [WIP](https://github.com/hbrls/docker-flask-app) too.

And I removed nginx recently because uwsgi can serve static files now. I'd like a discussion of the choice.

**Comment by tiangolo** [comment]
Great @hbrls !

Here's what I found before building it that way (with uWSGI and Nginx):

In the Flask docs it's said that: 

> uWSGI is a deployment option on servers like nginx, lighttpd, and cherokee; see FastCGI and Standalone WSGI Containers for other options.

 <http://flask.pocoo.org/docs/0.10/deploying/uwsgi/>

And based on the benchmarks in: <http://nichol.as/benchmark-of-python-web-servers> it seemed to me that **uWSGI** with **Nginx** would be on of the most robust ways to do a deployment with great performance.

Also, in uWSGI docs related to serving files directly it says that:

> Generally your webserver of choice (Nginx, Mongrel2, etc.) will serve static files efficiently and quickly and will simply forward dynamic requests to uWSGI backend nodes.

> The uWSGI project has ISPs and PaaS (that is, the hosting market) as the main target, where generally you would want to avoid generating disk I/O on a central server...

<https://uwsgi-docs.readthedocs.org/en/latest/StaticFiles.html>

...so it seems to me that making uWSGI serve files directly is in case you can't afford to set up a full web server (like Nginx) to do it. 

If someone was building a Docker container from scratch, the best bet would probably be starting with uWSGI alone to avoid more moving parts and another learning curve in Nginx configurations. 

But I think it would be worthwhile having a fully configured Docker image with all the niceties built in without having to learn and configure everything but getting all the possible performance and robustness... that's what I tried with this image I built.

What do you think?

**Comment by hbrls** [comment]
At first, I had only 1 app. So I had nginx in the image.

Then I had more and more apps,  and a standalone nginx container to dispatch outer most traffic. I just can not tolerate the "double nginx" solution.

See my question on [stackoverflow](http://stackoverflow.com/questions/25909985/whats-the-docker-pattern-of-serving-both-static-and-dynamic-content).

**Comment by tiangolo** [comment]
I see @hbrls.

But look, if people want to isolate servers and files and treat them as separated complete applications independent of having or not many other apps and an external server, they may want to have a simple complete container, as with the image I built.

They could build a Docker container and map its internal port to the port 80 of their VPS and just with that they will have a live application. It would be the simplest entry point for someone developing a Flask app and wanting to have the best performance with the least hand tuning.

If they need a more advanced and complex setup, having static files outsite of the Docker Flask app and configuring the external Nginx to serve those static files directly, they could then use your image  (once its finished) or build one from scratch. But they would have to have in mind that making the external Nginx be responsible for the static files and the Docker container for dynamic content would split the responsibilities of their app, and also would be risking each app to get broken because another app modified the Nginx configs while setting that another app's static data serving.

Also, have in mind that not everyone wants to setup one single Nginx to serve all static files and may want to have each Docker container be responsible for its own complete application, and maybe use something as [nginx-proxy](https://github.com/jwilder/nginx-proxy) to facilitate things and make it all more manageable.

I think my image could be used as a base use case approach for deployment, the first step in improving the performance to a deployment level of an app currently running as:

```
if __name__ == '__main__':
    app.run(host='0.0.0.0', port=80)
```

Then, for more advanced setups, I would suggest you to write a documentation page and submit a PR with all your recommendations for a bigger complex setup.

But I think the simplest base use case would be having one app, with its data in the same container and wanting it to have good performance.

Either way, I think Flask users would benefit from having at least one way to deploy with Docker without having to do all the work by hand and have it documented (or linked) in the official docs. 

Of course my image will not fit for every case (as it obviously doesn't fit yours), but for a novice that finally has his app running, it could be a first step in improving its performance to a "production" level without having to learn and configure a too big bunch of other parts and having it fully containerized and isolated from the external environment.

Anyway, I think you could add another issue suggesting what would you do to deploy a Flask app to production, or adding your Docker image, but the two approaches could work and could be documented, may be as "a third party base Docker image".

I think users would benefit more from "here are two approaches to deploy with Docker" than simply nothing in the docs.

**Comment by davidism** [comment]
I'd rather have users that understand the parts and configuration necessary for deployment, rather than hiding it all behind containers.  @tiangolo your version forces py27 and doesn't install requirements.  @hbrls your version trusts a bunch of third party repos.  Neither of these offer clear instruction about how to modify configuration, especially important for setting up uwsgi with multiple processes (which both versions inexplicably leave out), ssl, etc.  I'd rather leave this separate from official documentation rather than encouraging users to run scripts as root.

**Comment by tiangolo** [comment]
OK, thanks for the comment @davidism.

**Comment by hbrls** [comment]
@davidism The pypi server is because the official one is blocked in China. Sad.
