### ISSUE TITLE
Documentation download links for PDF and zipped HTML return 404s on http://flask.pocoo.org/

### ISSUE THREAD

**Issue by bretellis** [mitsuhiko/flask#1736]
I was trying to download the documentation from http://flask.pocoo.org/ using the PDF link and got a 404.  At the same time also tried the zipped HTML link and that returned a 404 as well.

**Comment by ThiefMaster** [comment]
duplicate of mitsuhiko/flask-website#16

**Comment by bretellis** [comment]
Thanks I searched first but didn't see that one.
