### ISSUE TITLE
JSONEncoder and aware datetimes

### ISSUE THREAD

**Issue by vitriol** [mitsuhiko/flask#1749]
I was surprised to see that though flask.json.JSONEncoder accepts datetime objects, it ignores the timezone. I checked werkzeug.http.http_date and it can handle timezone aware dates just fine if they are passed in, but the JSONEncoder insists on transforming the datetime to a timetuple, like this

 `return http_date(o.timetuple())`

This means i have to convert all my dates to utc before encoding them, otherwise I should overwrite the dafault() method in the encoder. Can you help me understand why the encoder was made to function with naive dates only?
Thx

**Comment by davidism** [comment]
You should always use UTC as the communication format, only use timezones for display.

**Comment by jdugge** [comment]
We have come across the same issue: in our application, `jsonify` is called for creating a representation of the `datetime` object to be shown to the user, so we convert our internal UTC-`datetime` object to a tz-aware `datetime` object in local time just before calling `jsonify`. However, the `.timetuple()` call throws away the timezone information, leading to incorrect output (the correct numerical value with `GMT` tagged on).

Removing `.timetuple()` in https://github.com/pallets/flask/blob/master/flask/json.py#L75 would fix this error, while leaving the behaviour for naive or UTC-`datetimes` unchanged.
