### ISSUE TITLE
Want to change the default server address for flask application 

### ISSUE THREAD

**Issue by khanstark** [mitsuhiko/flask#1756]
I did this-- `if __name__ == '__main__':
    app.run(host='0.0.0.0',port='80')`

but i get Permission denied error... couldn't find anything in the documentation. Is there any other way to accomplish this? It was relatively easier to do this in  django.
Thanks!

**Comment by ThiefMaster** [comment]
Why are you trying to run on 0.0.0.0:80? The dev server is not meant for production, and in development there's no reason to run in port 80 (which requires root permissions anyway, something you DO NOT want in your python app). Also, ports are numbers, not strings.

**Comment by khanstark** [comment]
even in the production server[127.0.0.1] i am unable to change port...i just wanted to know is it possible to change port number or not? Why i wanna do that is a secondary thing!

**Comment by ThiefMaster** [comment]
You SHOULD NOT use `app.run` in production at all!
And no, it's not a "secondary thing", because you will be back with other issues that will show up when using it in production.

Anyway, ports <=1024 need root permissions to bind, and you should not run your app as root, so you cannot use those ports. If you really need to run the dev server on port 80 put nginx in front of it so you can have that listen on 80 and keep your dev server on an unprivileged port.

**Comment by khanstark** [comment]
yeah i can use nginx to run on port 80...anyways i got it right by using 127.0.0.1 on ports >1024..
Thanks!

**Comment by Dmitry-KhMt** [comment]
If want change URL server, you can edit 2 files.

Windows: ...\Users\AppData\Local\Programs\Python\Python36-32\Lib\site-packages\flask\app.py

`if host is none`

**Comment by ThiefMaster** [comment]
@Dmitry-KhMt: Why would you do that?

**Comment by Dmitry-KhMt** [comment]
@ThiefMaster on the work-computer, port 5000 was busy. Here I just wrote how can change the port and the address, if suddenly it turns out to someone useful. On my laptop everything works fine on default 127.0.0.1:5000

**Comment by ThiefMaster** [comment]
But you do not need to edit a file. You can specify the port in `flask run` or `app.run()`.

**Comment by Dmitry-KhMt** [comment]
Thanks for the tip, I'll read how to do it right.
I recently began to study Python. I tried to solve the problem that appeared in a quick way. Apparently it is incorrect, although it gives the result
