### ISSUE TITLE
Is there a way to design blueprints to incorporate DELETE?

### ISSUE THREAD

**Issue by rlam3** [mitsuhiko/flask#1757]
Is there a way to design blueprints to incorporate DELETE?

I've been getting a error for a long time because I want to implement a form button action to just do a basic delete functionality for my app.

```
Method Not Allowed

The method is not allowed for the requested URL.
```

This is what my method looks like and nothing seems to be working...

```
@mod.route('/region/<region_id>', methods=['DELETE'])
def delete_region(region_id):
```

It seems as if Flask only does GET and POST not DELETE or PUT... And my only alternative is to do GET based DELETE methods as an alternative workaround... this however when logging proves to be not the best way to display my data and how it is modified or accessed. Any advice here? Thanks a bunch.

Also, I'm not making an API ... I just want to make a link to delete one specific entry.

```
GET based DELETE

@mod.route('/region/<region_id>/delete', methods=['GET'])
def delete_region(region_id):

```

References:
https://www.reddit.com/r/flask/comments/2ax1mf/af_delete_example/

**Comment by davidism** [comment]
DELETE requests work just fine, I can't reproduce your issue.  This isn't related to blueprints.  Browsers only support GET and POST methods for forms, but that's not an issue with Flask.  You can make DELETE requests (or other methods) using JavaScript.

**Comment by rlam3** [comment]
@davidism how did you reproduce this? the method=['DELETE'] doesn't work for me when i use forms. So only GET and POST requests are supported by flask-wtf? So are you recommending me to use GET based DELETE to as an endpoint?

**Comment by ThiefMaster** [comment]
Forms simply do not support anything besides POST and GET. This is a 
limitation of HTML itself and has nothing to do with flask.

**Never** use GET to modify data, especially in a destructive way. Either 
use JavaScript to send a DELETE request using XHR or use POST using a form.

**Comment by davidism** [comment]
> Browsers only support GET and POST methods for forms

Not sure why you tried a form with DELETE *after* I said this, and I never mentioned Flask-WTF, which has nothing to do with how browsers handle forms.

> You can make DELETE requests (or other methods) using JavaScript.

So that's what I'm suggestion, if it wasn't clear.

**Comment by rlam3** [comment]
@davidism Do you know if flask has something similar to the following like rails? 

maybe use something like data-method for a link instead of a form? 

http://laraveldaily.com/crud-how-to-avoid-building-whole-form-for-delete-button/

**Comment by Kareeeeem** [comment]
What I've seen others do, and have done myself, is adding a hidden field in your form named "_method" with the value "DELETE".  Then in you could check for it like this:
 ```
def method_is_delete(request):
    '''Workaround for a lack of delete method is the HTML spec for forms.'''
    return request.form.get('_method', '') == 'DELETE'

@app.route('/')
def index():
    if method_is_delete(request):
        # delete somehing
```

**Comment by rlam3** [comment]
@Kareeeeem this sounds like a pretty cool way to do it.. but when it comes to logging requests and data.. it would become a bit of an issue.

**Comment by jeffwidman** [comment]
In general, "how to" questions like this are a better fit over on StackOverflow. You'll also generally get faster answers over there too.
