### ISSUE TITLE
"Nothing is rendered"

### ISSUE THREAD

**Issue by mitsuhiko** [mitsuhiko/flask#182]
There seem to be a few situations left where "nothing is rendered and nothings is displayed" ends up for the user. This probably means that the debug mode was not enabled. We should probably add a stderr based error logging by default in production mode because of that or at least warn the user in the documentation more.

Related feedback issues:

* http://feedback.flask.pocoo.org/message/56

**Comment by untitaker** [comment]
Closing due to staleness.
