### ISSUE TITLE
PackageName==dev is required

### ISSUE THREAD

**Issue by mitsuhiko** [mitsuhiko/flask#205]
Right now ExtensionName==dev is required to be approved however supporting that turns out to be surprisingly hard if you have changing repository URLs. We should either drop this requirement or provide a script that updates all existing descriptions with new names.

Right now a lot of Pocoo stuff itself does not support ==dev.

**Comment by untitaker** [comment]
Fixed by https://github.com/mitsuhiko/flask/pull/1035
