### ISSUE TITLE
Document Creole syntax for snippets comments

### ISSUE THREAD

**Issue by SimonSapin** [mitsuhiko/flask#372]
The “new snippet” has a nice explanation for the Creole dialect that is used:

http://flask.pocoo.org/snippets/new/

But there is no such thing when adding a new snippet comment. A link to the new snippet page or the creole website in the comment form should be enough.

This is a follow-up on a mailing-list question: http://flask.pocoo.org/mailinglist/archive/2011/12/31/how-do-i-add-code-markers-to-snippets/

**Comment by untitaker** [comment]
Moved to https://github.com/pocoo/flask-snippets/issues/7
