### ISSUE TITLE
Documentation on IIS deployment.

### ISSUE THREAD

**Issue by untitaker** [mitsuhiko/flask#620]
Just for the record.

  - http://feedback.flask.pocoo.org/message/305
  - http://feedback.flask.pocoo.org/message/289

**Comment by davidism** [comment]
Feedback isn't available anymore and no one else has mentioned IIS in the last year.   I'm not familiar with IIS, but those official docs look pretty thorough, and also complicated enough that I'm not sure how we'd summarize and keep that up to date in our docs.  Closing for now, if anyone has further interest in this please open a new issue.

**Comment by davidism** [comment]
Compromising by adding the linked article to the deploy index.  41622c8d681a170f39df2ab8dff170d3b8d2d139
