### ISSUE TITLE
Several issues with the mailing list (librelist), time to look for an alternative?

### ISSUE THREAD

**Issue by sfermigier** [mitsuhiko/flask#682]
There are several issues currently with the mailing list on librelist:

0. The website (http://librelist.com/) is currently down. This might be transient, or this might be because the service has been slowly decaying over the last months.

1. The synchro to http://flask.pocoo.org/mailinglist/archive/ is broken since 2012/10/29.

2. I've been unsubscribed a few months ago due to transient a problem with my DNS. I have since tried many times to subscribe again with the same address, with no success. This may be a very specific problem, or this may be a manifestation of more general issues with the mailing list management system.

3. I have also tried registering with gmail adresses created just for the purpose of reading the Flask mailing list. I've had mixed successes, and I've also noticed that some of the emails I could see on the librelist.com archives were not delivered to my account(s).

4. AFAICT, traffic to the mailing list has been going down over approximately the last 2-3 months. This might be because interest in Flask is slowly fading away (if true, bad news for us Flask users), or this might be because of some of the technical issues I've mentioned above (or others), in which case proactive actions should be taken to keep users engaged.

For these reasons, I'm wondering if moving to another mailing list management platform would not be appropriate.

  S.

**Comment by jeffwidman** [comment]
Is this still an issue? 

I used to regularly get Flask messages, but for the past few months I haven't received a thing. Similarly, I also can't seem to send emails to the Flask list and no feedback on rejected/bounced. 

I'd seen the librelist issues and assumed it was the list that was borked, but I just checked the [archives](http://librelist.com/browser/flask/) and there's recent messages, so I'm not sure if I'm missing something or if Librelist works for some folks and borked for others.

**Comment by untitaker** [comment]
Please follow up in https://github.com/pocoo/metaflask/issues/60

**Comment by untitaker** [comment]
FWIW it's still broken for me, I've never recieved a message. I'm not sure if I'm subscribed or not, because Librelist is ignoring the mails I send to find that out.

**Comment by jeffwidman** [comment]
Thanks @untitaker - I also wanted to say thanks for stepping up to help with a lot of the Flask ecosystem.  Much appreciated.

**Comment by jeffwidman** [comment]
Just for anyone who stumbles across this later, we've now migrated the mailing list to https://mail.python.org/mailman/listinfo/flask/
