### ISSUE TITLE
blueprint.route methods argument typo throws unclear exception 

### ISSUE THREAD

**Issue by adamkal** [mitsuhiko/flask#760]
*route* method takes **options which catches all keyword arguments and passes it further to *url_rule_class* which -- in case of typo like 'method' instead of 'methods' -- leads to misleading exception:

```traceback
[..]
File "/[..]/python2.7/site-packages/flask/app.py", line 943, in add_url_rule
  rule = self.url_rule_class(rule, methods=methods, **options)
TypeError: __init__() got an unexpected keyword argument 'method'
```

**Comment by davidism** [comment]
I don't see a practical way to do this sort of typo checking in a general way, and don't think it's useful enough to justify the complexity.  PyCharm, and possibly other IDEs, detect the correct kwargs.  If you're not using the IDE, you're in the same situation here as you would be with any other code that uses this pattern.  If anyone has a good argument and suggestion for why and how this should work, please open a new issue.

**Comment by robinclark007** [comment]
@Ceasar  ,I'm new to the flask
'''
TypeError: __init__() got an unexpected keyword argument 'method'
'''
change method to methods works

**Comment by ThiefMaster** [comment]
It's methods, not method.

**Comment by dsantosp12** [comment]
3 years later and I had the same misspelling! I have been using Flask for more than a year and this have never happened to me hehe. Thanks @Ceasar

**Comment by jakhax** [comment]
6 years later my friend also had the same error . Thanks @Ceasar for saving us from hours of debugging.
