### ISSUE TITLE
Incomplete mod_wsgi documentation

### ISSUE THREAD

**Issue by djszapi** [mitsuhiko/flask#825]
I have been having issues for 3-4 days now to get a hello world up and running on the remote server. I figured out that it would be nice if there was a documentation from A-Z how to get that done and working.

http://flask.pocoo.org/docs/deploying/mod_wsgi/

The current documentation does not provide an example what to put into an exact python file, and what url to open up in the web browser to get the desired python module running on the remote server. It is okay to have references to other places if that is more logical, but the idea is to have a self-contained page which I can start reading, and by I reach the end, I will have a working remote hello world.

This would be well appreciated.

**Comment by remram44** [comment]
:point_up: It looks like this non-constructive discussion about Apache configuration is over... close?

**Comment by untitaker** [comment]
I agree with @remram44 that there's nothing productive to get out of this discussion. Please open new issues for concrete suggestions.
